// Comprehensive help content for every page in the FundaMedical Sales Hub

export const PAGE_GUIDES = {
  Dashboard: {
    title: "Dashboard",
    icon: "📊",
    description: "Your real-time command centre for sales performance, meetings, and tasks.",
    overview: "The Dashboard gives you an at-a-glance view of everything happening in your business unit — from upcoming appointments and pending follow-ups to revenue targets and recent client activity.",
    steps: [
      "View your top KPI cards: active clients, upcoming appointments, pending follow-ups, and target progress.",
      "Click any KPI card to drill down into the underlying records.",
      "Review Upcoming Appointments to see your scheduled meetings for the next 7 days.",
      "Check the Pending Follow-Ups widget to act on overdue or due-today tasks.",
      "Use the BUL Performance chart to track your monthly actuals vs targets.",
      "Scroll down for recent contracts, pricing proposals, and client alerts.",
    ],
    features: [
      "Real-time KPI cards with drill-down capability",
      "Upcoming appointments panel with quick-confirm attendance",
      "Pending follow-ups sorted by urgency",
      "Revenue vs target progress bars",
      "Recent activity feed for your clients",
    ],
    tips: [
      "Bookmark the Dashboard as your default start page.",
      "Green metrics = on target; amber = close; red = attention needed.",
      "Click 'See All' on any panel to go to the full list view.",
    ],
    roles: "All roles — content filtered by your permissions.",
  },

  Clients: {
    title: "Law Firms (Clients)",
    icon: "👥",
    description: "Manage your full client portfolio — add, edit, and organise all law firm accounts.",
    overview: "The Clients page is your CRM hub for all FundaMedical law firm accounts. You can view, search, filter, and update every client record including contacts, financial details, and activity status.",
    steps: [
      "Use the search bar at the top to find a firm by name, BUL, or city.",
      "Click 'Add New Client' to create a new firm record manually.",
      "Use 'Onboarding Wizard' for a guided step-by-step client creation flow.",
      "Click any client card or row to open the full client detail view.",
      "In the detail view, edit firm info, add directors/attorneys, set activity status.",
      "Use filters (Province, BUL, Status) to narrow down large lists.",
    ],
    features: [
      "Multi-contact support: Directors, Attorneys, Legal Secretaries, Finance",
      "Activity status: ACTIVE / INACTIVE / Prospect",
      "GPS geocoding for client map integration",
      "Linked meeting history and follow-ups",
      "Export client data to Excel",
    ],
    tips: [
      "Always fill in the email and phone fields — needed for outreach and reminders.",
      "Set the correct BUL so the client appears in the right team dashboard.",
      "Use 'Prospect' status for firms not yet using FundaMedical services.",
      "Check the client map to plan efficient field visit routes.",
    ],
    roles: "Admin, Sales Manager, Senior Management, BUL, KAC — each sees their assigned clients.",
  },

  AppointmentTools: {
    title: "Appointment Tools",
    icon: "📅",
    description: "Schedule meetings, manage attendance, create minutes, and track follow-ups — all in one place.",
    overview: "Appointment Tools is your complete meeting management hub. Schedule new appointments, confirm attendance, log meeting minutes, create action items, and manage follow-ups — all linked to your client records.",
    steps: [
      "Click 'Schedule New Appointment' and select the client, date, time, and type.",
      "Choose appointment type: In-Person, Virtual, Phone Call, or Site Visit.",
      "Send attendance confirmation requests to all participants.",
      "After the meeting, click the appointment card and select 'Add Minutes'.",
      "Fill in the meeting minutes form with agenda, discussion notes, and action items.",
      "Create follow-up tasks directly from the minutes for any action items.",
    ],
    features: [
      "Calendar view for visual appointment scheduling",
      "Recurring appointment support",
      "Attendance confirmation tracking",
      "Auto-generated meeting reference numbers",
      "Pre-meeting brief generation (AI-powered)",
      "Action items linked to appointments",
      "WhatsApp team notification panel",
    ],
    tips: [
      "Use the calendar view to avoid scheduling conflicts.",
      "Mark attendance confirmed immediately when clients respond.",
      "Add meeting minutes on the same day — details are fresher.",
      "Link action items to specific team members with due dates.",
      "Use the 'Pre-Meeting Brief' to prepare before important meetings.",
    ],
    roles: "BUL, KAC, Admin, Sales Manager — creation filtered by assigned team.",
  },

  LeadSearch: {
    title: "Lead Search",
    icon: "🔍",
    description: "AI-powered discovery of new law firm leads, PI expert witnesses, and med neg witnesses.",
    overview: "Lead Search uses live internet search and AI to find potential new clients and expert witnesses for FundaMedical. Search by location and specialty to discover firms and experts you can target for outreach.",
    steps: [
      "Select your search mode: Law Firms, Medical Experts, Med Neg Witnesses, or view Saved Leads.",
      "For Law Firms: enter a city/town and/or select a province, then choose a specialty.",
      "Click 'Find Law Firms' and wait for AI-powered results (uses live web search).",
      "Review each result card — quality rating, specialties, court roll activity, and contact info.",
      "Click 'Save to DB' on any lead to add it to your Lead Database for follow-up.",
      "Select firms with the checkbox, then use 'Outreach' or 'Create Proposal' for selected firms.",
      "Use the 'Saved Leads' tab to view and manage all previously saved leads.",
    ],
    features: [
      "AI-powered live web search for real law firms",
      "Law Firms: PI/Med Neg/COIDA specialist focus",
      "Medical Experts: HPCSA-verified, SAMLA-registered experts",
      "Med Neg Witnesses: Court-tested expert witnesses from case records",
      "BUL territory allocation suggestion based on results",
      "Outreach email generation (AI-drafted)",
      "Proposal PDF generation for selected firms",
      "Export all results to Excel",
      "Cross-reference against existing client database",
    ],
    tips: [
      "Firms already in your client database are automatically flagged — focus on new ones.",
      "High quality rating = firm most likely to need FundaMedical services.",
      "Save leads immediately — search results are not stored automatically.",
      "Use 'Saved Leads' tab to track outreach outcomes and update contact status.",
      "For experts, filter by discipline and province for most relevant results.",
    ],
    roles: "All sales roles — BUL, KAC, Sales Manager.",
  },

  LeadDatabase: {
    title: "Lead Database",
    icon: "🗄️",
    description: "View and manage all saved leads across law firms and expert witnesses.",
    overview: "The Lead Database stores all leads you've saved from Lead Search. Track contact outcomes, assign to BULs, update status, and export for reporting.",
    steps: [
      "Use the filter bar to narrow leads by type, province, quality, or contact status.",
      "Click the edit (pencil) icon on any lead card to update contact details or outcomes.",
      "Change contact outcome to: Interested, Not Interested, No Response, Follow-Up Required, or Converted.",
      "Assign a BUL to each lead for ownership and follow-up responsibility.",
      "Use 'Export to Excel' to download a full report of your lead pipeline.",
    ],
    features: [
      "Filter by lead type (Law Firm / PI Expert / Med Neg Expert)",
      "Contact outcome tracking with colour-coded badges",
      "BUL assignment per lead",
      "HPCSA and SAMLA status indicators for expert leads",
      "Excel export of full database",
    ],
    tips: [
      "Update contact outcome after every interaction.",
      "Converted leads should eventually become full Client records.",
      "Use quality rating to prioritise your outreach order.",
    ],
    roles: "All sales roles.",
  },

  Finance: {
    title: "Finance Tools",
    icon: "💰",
    description: "Monitor client statements, deposits, balances, and aging analysis.",
    overview: "Finance Tools give you a complete view of client financial standing — monthly statements, deposit aging, balance tracking, and settlement requests. Data is imported monthly from X3.",
    steps: [
      "Select the import month using the month selector at the top.",
      "Use the search bar to find a specific law firm.",
      "Filter by Business Unit, BUL, or KAC to focus on your team's accounts.",
      "Click any statement row to expand full aging breakdown and comments.",
      "Add or update comments in the KAC Feedback field for each client.",
      "Use table or card view depending on your preference.",
    ],
    features: [
      "Monthly statement data imported from X3",
      "Deposit and balance aging analysis (0-18, 19-24, 25-36, 37-47, 48+ months)",
      "GREEN/ORANGE account status indicators",
      "KAC feedback fields per client",
      "Export filtered statements to Excel",
      "Finance Dashboard with graphical KPIs",
    ],
    tips: [
      "GREEN = account in good standing, ORANGE = needs attention.",
      "Filter by your team before exporting to avoid massive files.",
      "Add KAC feedback notes after every finance-related client call.",
      "Use Finance Dashboard for management-friendly charts and trends.",
    ],
    roles: "Finance Clerk, KAC, BUL, Admin, Finance Manager.",
  },

  ExpensesHub: {
    title: "Expenses Hub",
    icon: "🧾",
    description: "Log, manage, and report on business expenses and mileage.",
    overview: "Track all your business expenses in one place. Add expenses with receipts, log mileage for field trips, and export reports for reimbursement.",
    steps: [
      "Click 'Add Expense' to log a new business expense.",
      "Select category (Travel, Meals, Accommodation, etc.), enter amount and date.",
      "Upload a receipt photo or file for documentation.",
      "Link the expense to a client if applicable.",
      "For mileage, use the Mileage tab — log start/end locations and odometer readings.",
      "Export your expenses for the month to submit for reimbursement.",
    ],
    features: [
      "Receipt upload and storage",
      "Category-based expense tracking",
      "Client-linked expenses for accountability",
      "Mileage log with automatic distance calculation",
      "Status tracking: Pending / Approved / Rejected",
      "Monthly export to Excel",
    ],
    tips: [
      "Log expenses the same day — don't let them accumulate.",
      "Always attach a receipt photo for amounts over R200.",
      "Link to the relevant client for audit trail purposes.",
    ],
    roles: "BUL, KAC, Admin — managers can approve/reject.",
  },

  Contracts: {
    title: "Contract Tools",
    icon: "📄",
    description: "Create, send, and track client contracts and pricing proposals.",
    overview: "Manage the full contract lifecycle — from drafting using templates to sending for e-signature and tracking completion. Also create and send pricing proposals to prospective clients.",
    steps: [
      "Navigate to Contracts and click 'New Contract' or choose a template.",
      "Select the client and fill in contract details and pricing terms.",
      "Review the contract draft, then click 'Send for Signature'.",
      "The client receives an email with a signing link.",
      "Track status: Draft → Sent → Signed / Declined / Expired.",
      "For pricing proposals, use the Pricing Proposals tab and generate a PDF.",
    ],
    features: [
      "Contract templates for consistent formatting",
      "Digital e-signature capability",
      "Status tracking through the full contract lifecycle",
      "PDF generation and email delivery",
      "Pricing proposal creation and export",
      "Contract expiry tracking",
    ],
    tips: [
      "Always set an expiry date on contracts to prompt renewals.",
      "Use templates to ensure all required clauses are included.",
      "Follow up 7 days after sending if no signature received.",
    ],
    roles: "BUL, KAC, Admin, Sales Manager.",
  },

  MeetingRecordings: {
    title: "Recordings & Documents",
    icon: "🎙️",
    description: "Upload, store, and transcribe meeting recordings and documents.",
    overview: "Store all meeting recordings, documents, and attachments linked to client meetings. Auto-transcription is available for audio files.",
    steps: [
      "Navigate to Recordings & Documents from the sidebar.",
      "Click 'Upload' to add a new recording or document.",
      "Link the file to a specific meeting or client.",
      "For audio files, click 'Transcribe' to generate an AI transcription.",
      "Review and edit the transcription, then save it to the meeting minutes.",
    ],
    features: [
      "Audio and video recording upload",
      "AI-powered transcription",
      "Document storage linked to meetings/clients",
      "Search across all stored files",
    ],
    tips: [
      "Upload recordings immediately after meetings while details are fresh.",
      "Review AI transcriptions for accuracy before saving to minutes.",
      "Use descriptive file names for easy retrieval later.",
    ],
    roles: "BUL, Admin, Sales Manager.",
  },

  FieldVisits: {
    title: "Field Visits",
    icon: "📍",
    description: "Log and track field visits with GPS check-in and outcomes.",
    overview: "Record every field visit with GPS location capture, check-in/out times, visit outcomes, and photos. Links to meeting minutes for a complete visit record.",
    steps: [
      "Click 'Log New Visit' and select the client you're visiting.",
      "Allow location access for GPS check-in when you arrive.",
      "Record visit type, start time, and initial notes.",
      "When leaving, record check-out time and visit outcome.",
      "Add photos and outcome notes before submitting.",
      "Link to meeting minutes if a formal meeting was held.",
    ],
    features: [
      "GPS location capture at check-in",
      "Duration auto-calculation",
      "Visit outcome tracking (Positive/Neutral/Negative/No Contact)",
      "Photo upload for visit evidence",
      "Link to meeting minutes",
      "Client map integration",
    ],
    tips: [
      "Always check in via the app when you arrive — GPS timestamp is your record.",
      "Add outcome notes before you leave the premises.",
      "Take a photo of the firm's exterior as proof of visit.",
    ],
    roles: "BUL, KAC — managers can view all team visits.",
  },

  Analytics: {
    title: "Analytics",
    icon: "📈",
    description: "Company-wide performance analytics, trends, and KPI tracking.",
    overview: "Analytics provides deep-dive charts and tables across sales, appointments, client activity, and finance. Use filters to drill down by team, period, or individual BUL.",
    steps: [
      "Use the period selector to choose your analysis window (month/quarter/year).",
      "Select a specific BUL or view all teams using the team filter.",
      "Review appointment trends, follow-up completion rates, and client engagement.",
      "Click on chart segments to drill down into the underlying records.",
      "Export any chart or table to PDF or Excel.",
    ],
    features: [
      "Appointment volume and completion trends",
      "Follow-up completion rates by team",
      "Client engagement scores",
      "Revenue vs target charts",
      "Drill-down capability on all charts",
    ],
    tips: [
      "Compare month-on-month for trend spotting.",
      "Low engagement scores identify clients at risk of churn.",
      "Export charts for inclusion in management reports.",
    ],
    roles: "Admin, Sales Manager, Senior Management.",
  },

  BULPerformance: {
    title: "BUL Performance",
    icon: "🏆",
    description: "Individual BUL performance reports with targets vs actuals.",
    overview: "BUL Performance shows each Business Unit Leader's monthly results against their targets — bookings, revenue, client visits, and more.",
    steps: [
      "Select the month and BUL from the filter at the top.",
      "Review the KPI summary cards for key metrics.",
      "Scroll down for the detailed breakdown by service category.",
      "Compare actuals vs targets in the progress bars.",
      "Click 'Generate Report' to create a PDF performance report.",
    ],
    features: [
      "Monthly target vs actual comparison",
      "Multi-metric performance tracking",
      "PDF report generation",
      "Historical month comparison",
      "Team-level aggregated view",
    ],
    tips: [
      "Use this at your weekly team reviews.",
      "Flag any metric below 70% target early in the month.",
    ],
    roles: "Admin, Sales Manager, Senior Management, BUL (own data only).",
  },

  UserManagement: {
    title: "User Management",
    icon: "👤",
    description: "Invite, manage, and control access for all system users.",
    overview: "User Management lets admins invite new users, assign roles, update profiles, and deactivate accounts. Role assignment controls what each user can see and do in the system.",
    steps: [
      "Click 'Invite User' to send an email invitation to a new team member.",
      "Enter their email address and select their role.",
      "Once they accept, find them in the user list and complete their profile.",
      "Use 'Edit' to change role, name, or deactivate the account.",
      "Use 'Delete' (with caution) to permanently remove a user.",
    ],
    features: [
      "Email-based invitation system",
      "Role-based access control (Admin, BUL, KAC, Finance, etc.)",
      "Bulk user import via CSV",
      "User activity log for audit trail",
    ],
    tips: [
      "Assign the most restrictive role that still lets the user do their job.",
      "Deactivate rather than delete when staff leave — preserves history.",
      "Review user list monthly to remove inactive accounts.",
    ],
    roles: "Admin only.",
  },

  Marketing: {
    title: "Marketing Materials",
    icon: "📢",
    description: "Store and access all FundaMedical marketing collateral.",
    overview: "Central repository for all marketing materials — brochures, presentations, case studies, and service guides. Easy to access and share during client meetings.",
    steps: [
      "Browse materials by category or use the search bar.",
      "Click any material card to preview or download.",
      "Admins can upload new materials using the 'Upload' button.",
      "Share a direct link to materials from the material detail view.",
    ],
    features: [
      "Categorised material library (Brochures, Presentations, etc.)",
      "File preview and download",
      "Service area tagging",
      "Admin upload and management",
    ],
    tips: [
      "Download relevant materials to your device before field visits (offline access).",
      "Keep materials updated — outdated pricing causes confusion.",
    ],
    roles: "All roles can view; Admin can upload/manage.",
  },

  Experts: {
    title: "Expert Panel",
    icon: "🩺",
    description: "View and manage FundaMedical's panel of medical experts.",
    overview: "Browse the full panel of HPCSA-registered medical experts available for medico-legal reports. View qualifications, specializations, contact details, and availability cohort.",
    steps: [
      "Search by name or discipline using the search bar.",
      "Filter by specialty or active status to find available experts.",
      "Click an expert card to view full profile — bio, qualifications, publications.",
      "Use the cohort indicator to understand rotation availability.",
      "Admins can add new experts or update existing profiles.",
    ],
    features: [
      "Full expert profiles with qualifications and publications",
      "Discipline and specialty filtering",
      "Rotation cohort tracking",
      "Contact information management",
      "Activity status (Active/Semi-Active/Inactive)",
    ],
    tips: [
      "Check cohort availability before scheduling expert appointments.",
      "Use expert profiles to brief clients on who will assess their matter.",
    ],
    roles: "All authenticated users can view; Admin/Manager can edit.",
  },

  CollectionsReport: {
    title: "Collections Report",
    icon: "📋",
    description: "Track call logs, payment promises, and collection follow-ups.",
    overview: "The Collections Report shows all call logs, promise-to-pay dates, and collection outcomes for client accounts. Used by finance clerks to manage debt collection.",
    steps: [
      "Select the import month to view that period's collection data.",
      "Filter by Business Unit or finance clerk to focus on your accounts.",
      "Review each row for deposit and balance PTP dates.",
      "Update feedback and forecast balance fields after client calls.",
      "Export to Excel for management reporting.",
    ],
    features: [
      "Monthly call log import",
      "Promise-to-pay date tracking",
      "Forecast balance field",
      "KAC and DC feedback columns",
      "Excel export",
    ],
    tips: [
      "Always update PTP dates after every collection call.",
      "Flag 'Rec in Bank' once payment is confirmed.",
    ],
    roles: "Finance Clerk, KAC, Admin, Finance Manager.",
  },

  MonthlyImportHub: {
    title: "Monthly Import Hub",
    icon: "📥",
    description: "Import monthly data files for statements, collections, CBR, and more.",
    overview: "The Monthly Import Hub is where all monthly financial and operational data gets imported into the system — statements, CBR payments, call logs, and company targets.",
    steps: [
      "Select the data type you want to import (Statements, Call Logs, CBR, etc.).",
      "Download the required template if you don't have the file in the right format.",
      "Upload your Excel or CSV file using the file picker.",
      "Review the validation preview — fix any errors flagged before confirming.",
      "Click 'Confirm Import' to load the data into the database.",
    ],
    features: [
      "Multi-type import support (Statements, CBR, Targets, etc.)",
      "Pre-import validation with error flagging",
      "Template downloads for each import type",
      "Import history log",
    ],
    tips: [
      "Always run imports on the 1st working day of the month.",
      "Double-check the month identifier column before importing.",
      "If an import fails validation, download the error report to see what needs fixing.",
    ],
    roles: "Admin, Finance Manager.",
  },

  HealthChecker: {
    title: "Health Checker",
    icon: "🏥",
    description: "System health dashboard showing data quality and alert summaries.",
    overview: "Health Checker monitors the quality of data in the system — identifying missing fields, inactive clients with no recent contact, unresolved alerts, and other data integrity issues.",
    steps: [
      "Review the health score summary at the top.",
      "Expand each category to see specific records with issues.",
      "Click any flagged record to jump directly to the edit screen.",
      "Resolve each issue and refresh to update the health score.",
    ],
    features: [
      "Overall health score percentage",
      "Missing contact info detection",
      "Inactive client flagging",
      "Unresolved follow-up alerts",
      "Data completeness checks",
    ],
    tips: [
      "Run Health Checker at the start of each month.",
      "Prioritise fixing client records missing email/phone — needed for outreach.",
    ],
    roles: "Admin, Sales Manager.",
  },

  Goals: {
    title: "Goals",
    icon: "🎯",
    description: "Set, track, and review personal and team goals.",
    overview: "The Goals module lets BULs and managers set personal performance goals, track progress, and link goals to measurable outcomes.",
    steps: [
      "Click 'New Goal' to create a personal or team goal.",
      "Set a title, description, target metric, and deadline.",
      "Update progress as you achieve milestones.",
      "Mark goals complete when achieved.",
    ],
    features: [
      "Personal and team goal types",
      "Progress tracking with milestones",
      "Deadline reminders",
      "Goal completion history",
    ],
    tips: [
      "Link goals to your monthly targets for alignment.",
      "Review and update goals at least weekly.",
    ],
    roles: "All roles.",
  },

  ClientMapPage: {
    title: "Client Map",
    icon: "🗺️",
    description: "Visualise all clients geographically for field visit planning.",
    overview: "The Client Map shows all active clients plotted on a map of South Africa. Use it to plan efficient field visit routes and identify geographic clusters of clients.",
    steps: [
      "The map loads with all geocoded clients as pins.",
      "Click any pin to see the client's name and quick details.",
      "Use the filter panel to show only your assigned clients.",
      "Toggle between client activity status layers.",
      "Zoom in to plan visit routes by area.",
    ],
    features: [
      "Interactive map with client pin markers",
      "Client detail popup on pin click",
      "Filter by BUL, status, or province",
      "Geocoded from client address data",
    ],
    tips: [
      "Plan visits by geographic cluster to minimise travel time.",
      "Clients with no GPS coordinates won't appear — update their address.",
    ],
    roles: "BUL, KAC, Admin, Sales Manager.",
  },

  MessageCentre: {
    title: "Message Centre",
    icon: "💬",
    description: "Internal team messaging and channel collaboration.",
    overview: "Message Centre provides internal team communication through channels and direct messages. Keep your team coordination in one place without switching to external tools.",
    steps: [
      "Select a channel from the left panel or start a direct message.",
      "Type your message and press Enter or click Send.",
      "Use @ mentions to notify specific team members.",
      "Attach files or images using the attachment button.",
      "Create new channels for specific projects or teams.",
    ],
    features: [
      "Team channels and direct messaging",
      "File and image sharing",
      "@ mention notifications",
      "Message history and search",
    ],
    tips: [
      "Use channels for team-wide announcements, DMs for 1:1 coordination.",
      "Search message history before asking repeated questions.",
    ],
    roles: "All roles.",
  },

  BULManagement: {
    title: "BUL Management",
    icon: "👔",
    description: "Comprehensive BUL team management — targets, reports, and coaching.",
    overview: "BUL Management is the central hub for managing your Business Unit Leaders. Set targets, review performance reports, manage leave, and access AI coaching insights.",
    steps: [
      "Select a BUL from the list to view their full management profile.",
      "Review their daily actuals, meeting history, and target progress.",
      "Use the Performance Reports tab to generate monthly PDF reports.",
      "Access the AI Coaching panel for personalised improvement suggestions.",
      "Approve or reject leave requests from the Leave tab.",
    ],
    features: [
      "Daily actuals input and tracking",
      "Monthly performance PDF reports",
      "AI coaching insights per BUL",
      "Leave request management",
      "Target setting and tracking",
    ],
    tips: [
      "Use AI coaching suggestions during monthly 1:1 reviews.",
      "Generate performance reports before every management meeting.",
    ],
    roles: "Admin, Sales Manager, Senior Management.",
  },

  TeamCalendar: {
    title: "Team Calendar",
    icon: "📆",
    description: "View all team appointments in a shared calendar view.",
    overview: "The Team Calendar shows all appointments across your entire team in a shared view. Useful for managers to see team availability and scheduling gaps.",
    steps: [
      "Use the calendar navigation to switch between week and month views.",
      "Filter by BUL to focus on a specific team member's schedule.",
      "Click any event to see appointment details.",
      "Use the 'Add Event' button to create a new appointment.",
    ],
    features: [
      "Month and week calendar views",
      "Team-wide appointment visibility",
      "Filter by team member",
      "Event detail popup",
      "Integration with Appointment Tools",
    ],
    tips: [
      "Use month view for planning, week view for daily execution.",
      "Gaps in the calendar are outreach opportunities.",
    ],
    roles: "Admin, Sales Manager, BUL.",
  },

  FirmReferenceTable: {
    title: "Firm Reference Table",
    icon: "📊",
    description: "Master reference table mapping firm names across X3, tracking, and dropdown systems.",
    overview: "The Firm Reference Table is the master mapping of all client firm names as they appear in X3, the tracking site, and dropdown menus. Used to resolve name discrepancies across systems.",
    steps: [
      "Search for a firm to see how its name appears across all systems.",
      "Use this as the source of truth when names don't match on imports.",
      "Admins can update mappings when firm names change.",
      "Export the full table for reference use in Excel imports.",
    ],
    features: [
      "X3 account number lookup",
      "Finance name vs tracking name mapping",
      "BUL and DC-STM assignment reference",
      "Excel import/export",
    ],
    tips: [
      "Always check this table when an import fails due to unknown firm names.",
      "Keep the table updated when clients rebrand or merge.",
    ],
    roles: "Admin, Finance Manager, Import operators.",
  },

  UserProfile: {
    title: "Settings / Profile",
    icon: "⚙️",
    description: "Manage your personal profile, notifications, and integrations.",
    overview: "Update your personal details, configure notification preferences, manage calendar integrations, and set your display preferences.",
    steps: [
      "Update your full name, phone number, and profile photo.",
      "Go to Notifications tab to configure which alerts you receive.",
      "Use Integrations tab to connect Google Calendar or Outlook.",
      "Save all changes using the Save button at the bottom.",
    ],
    features: [
      "Personal profile editor",
      "Notification preference controls",
      "Calendar integration (Google / Outlook)",
      "Admin permission controls",
    ],
    tips: [
      "Keep your profile up to date — your name appears on meeting minutes and reports.",
      "Connect your calendar to sync appointments automatically.",
    ],
    roles: "All roles (own profile only).",
  },

  MeetingAnalyticsDashboard: {
    title: "Meeting Analytics",
    icon: "📊",
    description: "Analyse meeting patterns, frequency, and outcomes across the team.",
    overview: "Meeting Analytics provides detailed insight into appointment and meeting data — frequency, types, outcomes, and geographic distribution.",
    steps: [
      "Select the date range and team to analyse.",
      "Review the meeting frequency chart and compare to targets.",
      "Check the outcomes breakdown (completed, cancelled, rescheduled).",
      "Use the geographic heat map to see where most meetings are held.",
    ],
    features: [
      "Meeting frequency trends",
      "Outcome distribution charts",
      "Geographic heat map",
      "Drill-down to individual meeting records",
    ],
    tips: [
      "High cancellation rates indicate scheduling or attendance issues — investigate.",
      "Use geographic view to identify underserved regions.",
    ],
    roles: "Admin, Sales Manager, Senior Management.",
  },

  ActionItemsDashboard: {
    title: "Action Items",
    icon: "✅",
    description: "Track and manage all action items from meetings across the team.",
    overview: "Action Items Dashboard aggregates all action items created from meeting minutes across all teams. Filter by status, assignee, or due date to manage outstanding tasks.",
    steps: [
      "Filter by status (Open/In Progress/Completed) to find items needing attention.",
      "Click any item to view context from the original meeting minutes.",
      "Update item status as work progresses.",
      "Filter by assignee to see your personal action item list.",
    ],
    features: [
      "Aggregated action items from all meetings",
      "Status tracking (Open/In Progress/Completed/Overdue)",
      "Linked back to source meeting minutes",
      "Filter by assignee and due date",
    ],
    tips: [
      "Review your personal action items every morning.",
      "Overdue items in red need immediate attention.",
    ],
    roles: "All roles — each sees their own items; managers see all.",
  },

  FinanceDashboard: {
    title: "Finance Dashboard",
    icon: "💹",
    description: "Graphical overview of financial KPIs, aging, and payment trends.",
    overview: "The Finance Dashboard presents all key financial metrics in graphical format — aging analysis, deposit vs balance trends, payment status distribution, and monthly movements.",
    steps: [
      "Select the import month to view that period's financial overview.",
      "Review the top KPI cards for total due, deposits, balances.",
      "Scroll down for aging analysis charts and payment status distribution.",
      "Use filters to drill down by business unit or BUL.",
    ],
    features: [
      "Monthly KPI summary cards",
      "Aging analysis by bucket (0-18, 19-24, etc.)",
      "Payment status distribution pie chart",
      "Month-on-month trend charts",
      "Business unit comparison",
    ],
    tips: [
      "Focus on the 48+ month aging bucket first — highest risk.",
      "Compare month-on-month to spot deteriorating accounts.",
    ],
    roles: "Finance Clerk, Admin, Finance Manager, Senior Management.",
  },
};