import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

// Normalize a name for fuzzy matching
function norm(s) {
  if (!s || s === '#N/A') return '';
  return s.toUpperCase()
    .replace(/\s+/g, ' ')
    .replace(/[&]/g, 'AND')
    .replace(/[^A-Z0-9 ]/g, '')
    .replace(/\b(INC|INCORPORATED|ATTORNEYS|ATTORNEY|ATT|AND|THE|PTY|LTD|CF|MF)\b/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Levenshtein distance
function lev(a, b) {
  const m = a.length, n = b.length;
  const dp = Array.from({ length: m + 1 }, (_, i) => [i, ...Array(n).fill(0)]);
  for (let j = 0; j <= n; j++) dp[0][j] = j;
  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      dp[i][j] = a[i-1] === b[j-1] ? dp[i-1][j-1] : 1 + Math.min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]);
    }
  }
  return dp[m][n];
}

function similarity(a, b) {
  const na = norm(a), nb = norm(b);
  if (!na || !nb) return 0;
  if (na === nb) return 1;
  if (na.includes(nb) || nb.includes(na)) return 0.9;
  const dist = lev(na, nb);
  const maxLen = Math.max(na.length, nb.length);
  return maxLen > 0 ? 1 - dist / maxLen : 0;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin only' }, { status: 403 });
    }

    // Raw data from the spreadsheet - all rows parsed
    const rawRows = [
      { acc: 'ABA001', fin: 'A Batchelor And Associates', trk: 'A BATCHELOR AND ASSOCIATES', dd: 'A BATCHELOR & ASSOCIATES', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'AND002', fin: 'A Ndlovu Attorneys Inc', trk: 'A NDLOVU ATTORNEYS INC', dd: 'A NDLOVU ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'WOL001', fin: 'A Wolmarans Inc', trk: 'A WOLMARANS INC', dd: '', status: 'Financed (Other)', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'WOL1MF', fin: 'A Wolmarans Inc (MF)', trk: '', dd: '', status: 'Financed (Other)', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'SCH003', fin: 'A Wolmarans Inc (Schumanns)', trk: 'A WOLMARANS INC (SCHUMANNS)', dd: '', status: 'Priority', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'ACD001', fin: 'AC De Sousa Attorneys', trk: 'AC DE SOUSA ATTORNEYS', dd: 'AC DE SOUSA ATTORNEYS', status: 'Priority', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ACD1CF', fin: 'AC De Sousa Attorneys (CF)', trk: '', dd: '', status: 'Financed (CF)', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ADA001', fin: 'Adams & Adams Attorneys', trk: 'ADAMS & ADAMS ATTORNEYS', dd: 'ADAMS & ADAMS ATTORNEYS', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ADE001', fin: 'Adele Jordaan Attorneys', trk: '', dd: 'ADELE JORDAAN ATTORNEYS', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ADE001', fin: 'Adendorff Theron Inc', trk: 'ADENDORFF THERON INC', dd: 'ADENDORFF THERON INC', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'ADV002', fin: 'Advocate DD Mosoma', trk: 'ADVOCATE DD MOSOMA', dd: 'ADV DD MOSOMA', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ADV001', fin: 'Advocate Masilo Eucon Sekgobela', trk: 'ADVOCATE MASILO EUCON SEKGOBELA', dd: 'ADV MASILO EUCON SEKGOBELA', status: 'Handed-over', stm: 'DINERO', inv: 'GAVIN', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'AFM001', fin: 'AF Mhaleni & Partners', trk: 'AF MHALENI & PARTNERS', dd: 'AF MHALENI & PARTNERS', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'AFR001', fin: 'Africa Dawn Risk Solutions (Pty) Ltd', trk: 'AFRICA DAWN RISK SOLUTIONS (PTY) LTD', dd: '', status: 'Password Protect', stm: 'COLEEN', inv: 'N/A', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'AJA001', fin: 'AJ Alderson Inc', trk: 'AJ ALDERSON INC', dd: 'AJ ALDERSON INC', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'AJA1CF', fin: 'AJ Alderson Inc (CF)', trk: '', dd: '', status: 'Financed (CF)', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'AJC001', fin: 'AJ Alderson Inc (Chueu)', trk: 'AJ ALDERSON INC (CHUEU)', dd: 'AJ ALDERSON INC (CHUEU)', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'AJA002', fin: 'AJ Ndwayamato Inc', trk: 'AJ NDWAYAMATO INC', dd: 'AJ NDWAYAMATO INC', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'ALW001', fin: 'Allan Wiedemann Attorneys Inc.', trk: '', dd: 'ALLAN WEIDEMAN ATTORNEYS INCORPORATED', status: 'Upfront', stm: 'COLEEN', inv: 'COLEEN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'ALL002', fin: 'Allnutt Sikhonde Attorneys', trk: 'ALLNUTT SIKHONDE ATTORNEYS', dd: 'ALLNUTT SIKHONDE ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'AML001', fin: 'AM Law Inc', trk: 'AM LAW INC', dd: 'AM LAW INC', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'AND001', fin: 'Andre Du Plessis Incorporated', trk: 'ANDRE DU PLESSIS INCORPORATED', dd: 'ANDRE DU PLESSIS', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'ANK001', fin: 'Anker Attorneys Inc', trk: 'ANKER ATTORNEYS INC', dd: 'ANKER ATTORNEYS INC', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'ANT001', fin: 'Anthony Wilton Thinane Inc.', trk: 'ANTHONY WILTON THINANE INC.', dd: 'ANTHONY WILTON THINANE INC', status: 'No Services', stm: 'DINERO', inv: 'KAVISHA', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'ANY001', fin: 'Anyiam Attorneys Inc', trk: 'ANYIAM ATTORNEYS INC', dd: 'ANYIAM ATTORNEYS INC', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'APA001', fin: 'Appelgryn Potgieter Attorneys', trk: 'APPELGRYN POTGIETER ATTORNEYS', dd: 'APPELGRYN POTGIETER', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'ART001', fin: 'Arthur van den Bergh Attorneys', trk: 'ARTHUR VAN DEN BERGH ATTORNEYS', dd: 'ARTHUR VAN BERGH ATTORNEYS', status: 'No Services', stm: 'PENDING', inv: 'PENDING', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ABS001', fin: 'AS Bosman', trk: 'AS BOSMAN', dd: 'AS BOSMAN', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'ABS1CF', fin: 'AS Bosman (CF)', trk: '', dd: '', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'AAI001', fin: 'Austin Allan Inc', trk: 'AUSTIN ALLAN INC', dd: 'AUSTIN ALLAN INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'AAICF', fin: 'Austin Allan Inc (CF)', trk: '', dd: '', status: 'Financed (CF)', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'THE002', fin: 'AV Theron & Swanepoel', trk: 'AV THERON & SWANEPOEL', dd: 'AV THERON & SWANEPOEL', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'BAD001', fin: 'Badenhorst Attorneys', trk: 'BADENHORST ATTORNEYS', dd: 'BADENHORST ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'BAL002', fin: 'Baloyi Maluleke Attorneys', trk: 'BALOYI MALULEKE ATTORNEYS', dd: 'BALOYI MALULEKE ATTORNEYS', status: 'Pre-booking payment', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'BAR003', fin: 'Bares & Basson', trk: 'BARES & BASSON', dd: 'BARES & BASSON', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'BAR002', fin: 'Barnard & Patel Inc', trk: 'BARNARD & PATEL INC', dd: 'BARNARD & PATEL INC', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'BEA001', fin: 'Beaumont Attorneys', trk: 'BEAUMONT ATTORNEYS', dd: 'BEAUMONT ATTORNEYS', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BER004', fin: 'Berkowitz Cohen Wartski', trk: 'BERKOWITZ COHEN WARTSKI', dd: 'BERKOWITZ COHEN WARTSKI ATTORNEYS', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BER4CF', fin: 'Berkowitz Cohen Wartski (CF)', trk: '', dd: '', status: 'Financed (CF)', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BER003', fin: 'Berndt and La Vita Incorporated', trk: 'BERNDT AND LA VITA INCORPORATED', dd: 'BERNDT AND LA VITA INCORPORATED', status: 'No Services', stm: 'PENDING', inv: 'PENDING', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BEZ003', fin: 'Bezuidenhout Inc', trk: 'BEZUIDENHOUT INC', dd: 'BEZUIDENHOUT INC', status: 'Password Protect', stm: '', inv: 'CHANTEL', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BEZ001', fin: 'Bezuidenhouts Attorneys', trk: 'BEZUIDENHOUTS ATTORNEYS', dd: 'BEZUIDENHOUTS', status: 'No Services', stm: '', inv: 'KAVISHA', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BHI001', fin: 'Bhika Calitz Attorneys', trk: 'BHIKA CALITZ ATTORNEYS', dd: 'BHIKACALITZ ATTORNEYS', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BIE002', fin: 'Bierman Smit Inc', trk: 'BIERMAN SMIT ATTORNEYS', dd: 'BIERMAN SMIT ATTORNEYS', status: 'Priority (Other)', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'BIG001', fin: 'Bigen Africa Services (Pty) Ltd', trk: 'BIGEN AFRICA SERVICES (PTY) LTD', dd: 'BIGEN', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'BOK001', fin: 'Bokwa Inc', trk: 'BOKWA INC', dd: 'BOKWA INC', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'BOO001', fin: 'Booyens Attorneys', trk: 'BOOYENS ATTORNEYS', dd: 'BOOYENS ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'BOR001', fin: 'Bornman Attorneys', trk: 'BORNMAN ATTORNEYS', dd: 'BORNMAN', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'BOS002', fin: 'Boshoff Inc', trk: 'BOSHOFF INC', dd: 'BOSHOFF INC', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'BSD001', fin: 'Bosman Dyasi Inc', trk: 'BOSMAN DYASI INC', dd: 'BOSMAN DYASI', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'BOV001', fin: 'Bove Attorneys Inc', trk: 'BOVE ATTORNEYS INC', dd: '', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'HEL001', fin: 'Breitenbach Attorneys', trk: 'BREITENBACH ATTORNEYS', dd: 'BREITENBACH', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'BRI001', fin: 'Brink De Beer & Potgieter Attorneys', trk: 'BRINK DE BEER & POTGIETER ATTORNEYS', dd: 'BRINK, DE BEER & POTGIETER', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'BTM001', fin: 'BT Maribolla Attorneys', trk: 'BT MARIBOLLA ATTORNEYS', dd: 'BT MARIBOLLA ATTORNEYS', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'BUR008', fin: 'Burger Huyser Attorneys', trk: 'BURGER HUYSER ATTORNEYS', dd: 'BURGER HUYSER ATTORNEYS', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'CAM003', fin: 'Campbell Attorneys (DBN)', trk: 'CAMPBELL ATTORNEYS (DBN)', dd: 'CAMPBELL - DBN', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'CAM001', fin: 'Campbell Attorneys (PTA)', trk: 'CAMPBELL ATTORNEYS (PTA)', dd: 'CAMPBELL - PTA', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'CBI001', fin: 'CBI Attorneys', trk: 'CBI ATTORNEYS', dd: 'CBI ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'CHA001', fin: 'Chambers_Van Der Westhuizen Attorneys', trk: 'CHAMBERS_VAN DER WESTHUIZEN ATTORNEYS', dd: 'CHAMBERS VAN DER WESTHUIZEN', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'CHA002', fin: 'Chaza Attorneys', trk: 'CHAZA ATTORNEYS', dd: 'CHAZA ATTORNEYS', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'CHU002', fin: 'Chuene Attorneys', trk: 'CHUENE ATTORNEYS', dd: 'CHUENE ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'CHU001', fin: 'Chueu Incorporated Attorneys', trk: 'CHUEU INCORPORATED ATTORNEYS', dd: 'CHUEU INC', status: 'Handed-Over', stm: 'FRANK', inv: 'FRANK', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'CLA002', fin: 'Claims Administrators Africa', trk: 'CLAIMS ADMINISTRATORS AFRICA', dd: 'CLAIMS ADMINISTRATORS AFRICA', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'CAT001', fin: 'Clive Unsworth Attorneys', trk: 'CLIVE UNSWORTH ATTORNEYS', dd: 'CLIVE UNSWORTH ATTORNEYS', status: 'Pre-booking payment', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'CLY001', fin: 'Clyde & Co', trk: 'CLYDE & CO', dd: 'CLYDE & CO', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'CLI001', fin: 'Cobus Leuvennink Ingelyf', trk: 'COBUS LEUVENNINK INGELYF', dd: 'COBUS LEUVENNINK INC', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'COE001', fin: 'Coetzee & Venter Attorneys', trk: 'COETZEE & VENTER ATTORNEYS', dd: 'COETZEE & VENTERS', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'COM001', fin: 'Combrink Nel And Ballack Inc', trk: 'COMBRINK NEL AND ASSOCIATES', dd: 'COMBRINK NEL AND ASSOCIATES', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'COR001', fin: 'Corne Nell Incorporated', trk: 'CORNE NELL INCORPORATED', dd: 'CORNE NELL', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'ANR001', fin: 'D Kaufmann Inc t/a Andersen', trk: 'D KAUFMANN INC T/A ANDERSEN', dd: '', status: 'No Services', stm: 'DORMANT', inv: 'DORMANT', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'DAV003', fin: 'David Maripane Inc', trk: 'DAVID MARIPANE INC', dd: 'DAVID MARIPANE INC', status: 'No Services', stm: 'DINERO', inv: 'GAVIN', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'DBV1MF', fin: 'DBVS Attorneys', trk: 'DBVS INCORPORATED', dd: 'DBVS ATTORNEYS', status: 'Financed (Other)', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'DEA002', fin: 'De Agrella Attorneys', trk: 'DE AGRELLA ATTORNEYS', dd: 'DE AGRELLA ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'DEB001', fin: 'De Broglio', trk: 'DE BROGLIO', dd: 'DE BROGLIO', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'DEB003', fin: 'De Bruyn & Smit Inc', trk: 'DE BRUYN & SMIT INC', dd: 'DE BRUYN & SMIT INC', status: 'Dormant', stm: 'SNOTHILE', inv: 'DORMANT', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'CHR001', fin: 'De Ridder Inc', trk: 'DE RIDDER INC', dd: 'DE RIDDER INC', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'DEW001', fin: 'De Waal Incorporated', trk: 'DE WAAL INCORPORATED', dd: 'DE WAAL INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'DIE001', fin: 'Diedricks Attorneys', trk: 'DIEDRICKS ATTORNEYS', dd: 'DIEDERICKS INC', status: 'No Services', stm: 'DORMANT', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'DOU01', fin: 'Douglas Bennet Inc', trk: 'DOUGLAS BENNETT INC', dd: 'DOUGLAS BENNET INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'DRE002', fin: 'Dreyer And Dreyer Attorneys', trk: 'DREYER AND DREYER ATTORNEYS', dd: 'DREYER AND DREYER ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'DSC001', fin: 'DSC Attorneys', trk: 'DSC ATTORNEYS', dd: 'DSC ATTORNEYS', status: 'No Services', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'DUP001', fin: 'Du Plessis Attorneys', trk: 'DU PLESSIS ATTORNEYS', dd: 'DU PLESSIS ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'GAVIN', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'NDP001', fin: 'Du Plooy Attorneys', trk: 'DU PLOOY ATTORNEYS', dd: 'DU PLOOY ATTORNEYS', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'DUD001', fin: 'Dudula Attorneys', trk: 'DUDULA ATTORNEYS', dd: 'DUDULA ATTORNEYS', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'DWM001', fin: 'DWM Attorneys', trk: 'DWM ATTORNEYS', dd: 'DWM ATTORNEYS', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'DYA002', fin: 'Dyason Incorporated', trk: 'DYASON INCORPORATED', dd: 'DYASON INCORPORATED', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'EBM001', fin: 'Eben Marais Inc', trk: 'EBEN MARAIS INC', dd: 'EBEN MARAIS INCORPORATED', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'EDE001', fin: 'Edeling Van Niekerk Inc Attorneys', trk: 'EDELING VAN NIEKERK INC ATTORNEYS', dd: 'EDELING VAN NIEKERK INC ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'EGC001', fin: 'EG Cooper Madjiedt Inc', trk: 'EG COOPER MADJIEDT INC', dd: 'EG COOPER MADJIEDT INC', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'EMM001', fin: 'EM Mmila Attorneys', trk: 'EM MMILA ATTORNEYS', dd: '', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'BIH01', fin: 'EMIL BIHL ATTORNEYS', trk: 'EMIL BIHL ATTORNEYS', dd: 'EMIL BIHL', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'EMF001', fin: 'Emil Faber Inc Attorneys', trk: 'EMIL FABER INC ATTORNEYS', dd: 'EMIL FABER INC ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'ENV001', fin: 'Enver Swartz Attorneys', trk: 'ENVER SWARTZ ATTORNEYS', dd: 'ENVER SWARTZ ATTORNEYS', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ERA002', fin: 'Erasmus De Klerk Inc', trk: 'ERASMUS DE KLERK INC', dd: 'ERASMUS DE KLERK INC', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'ERA001', fin: 'Erasmus Scheepers Attorneys', trk: 'ERASMUS SCHEEPERS ATTORNEYS', dd: 'ERASMUS SCHEEPERS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'EDE002', fin: 'EVN Legal Practitioners Inc', trk: 'EVN LEGAL PRACTITIONERS INC', dd: 'EVN LEGAL PRACTITIONERS INCORPORATED', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'FOD001', fin: 'Forder Van Wyk Pieterse Attorneys', trk: 'FORDER VAN WYK PIETERSE ATTORNEYS', dd: 'FORDER VAN WYK PIETERSE ATTORNEYS', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'FSM001', fin: 'Frans Schutte @ Matthews Phosa Inc', trk: 'FRANS SCHUTTE & MATTHEWS PHOSA', dd: 'FRANS SCHUTTE & MATTHEWS PHOSA', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'FRI001', fin: 'Frieda Scheepers Attorneys', trk: 'FRIEDA SCHEEPERS ATTORNEYS', dd: 'FRIEDA SCHEEPERS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'FRI003', fin: 'Friedman Attorneys', trk: 'FRIEDMAN ATTORNEYS', dd: 'FRIEDMAN ATTORNEYS', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'GGR001', fin: 'G Grobbelaar Incorporated', trk: 'G GROBBELAAR INCORPORATED', dd: 'G GROBBELAAR INCORPORATED', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'GAL001', fin: 'Galatis Inc Attorneys', trk: 'GALATIS INC ATTORNEYS', dd: 'GALATIS INC ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'GAR001', fin: 'Gary Austin Inc', trk: 'GARY AUSTIN INC', dd: 'GARY AUSTIN INC', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'GAV001', fin: 'Gaven Shela', trk: 'GAVEN SHELA ATTORNEYS', dd: 'GAVEN SHELA ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'GER006', fin: 'Gerhold & Van Wyk Attorneys', trk: 'GERHOLD & VAN WYK ATTORNEYS', dd: 'GERHOLD & VAN WYK ATTORNEYS', status: 'Pre-booking payment', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'GER001', fin: 'Gert Nel Incorporated', trk: 'GERT NEL INCORPORATED', dd: 'GERT NEL', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'GIL002', fin: 'Gildenhuys Malatji Attorneys - Greyling', trk: 'GILDENHUYS MALATJI ATTORNEYS - GREYLING', dd: 'GILDENHUYS MALATJI (GREYLING)', status: 'Priority', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'GIL003', fin: 'Gildenhuys Malatji Attorneys - Rakgadi', trk: 'GILDENHUYS MALATJI ATTORNEYS - RAKGADI', dd: 'GILDENHUYS MALATJI (RAGADI)', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'GIL002', fin: 'Gildenhuys Malatji Attorneys - Vlok', trk: 'GILDENHUYS MALATJI ATTORNEYS - VLOK', dd: 'GILDENHUYS MALATJI (VLOK)', status: 'Priority', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'GOD001', fin: 'Godi Attorneys', trk: 'GODI ATTORNEYS', dd: 'GODI', status: 'Password Protect', stm: 'DINERO', inv: 'MARISKA', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'GOO001', fin: 'Goodrich & Franklin', trk: 'GOODRICH & FRANKLIN', dd: 'GOODRICH & FRANKLIN', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'GOU001', fin: 'Gous Van Aarde Incorporated', trk: 'GOUS VAN AARDE INCORPORATED', dd: 'GOUSE VAN AARDE INCORPORATED', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'GNI001', fin: 'Grindlay Naidoo Inc', trk: 'GRINDLAY NAIDOO INC', dd: 'GRINDLAY NAIDOO INC', status: 'No Services', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'GSG001', fin: 'GSG Attorneys', trk: 'GSG ATTORNEYS', dd: 'GSG ATTORNEYS', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'HAD001', fin: 'Hadebe Attorneys', trk: 'HADEBE ATTORNEYS', dd: 'HADEBE', status: 'Password Protect', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'HAN002', fin: 'Hannes Pretorius, Bock & Bryant', trk: 'HANNES PRETORIUS, BOCK & BRYANT', dd: 'HANNES, PRETORIUS, BLOCK & BRYANT (RAF)', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'HAR002', fin: 'Hartmann & Associates', trk: 'HARTMANN & ASSOCIATES', dd: 'HARTMAN & ASSOCIATES', status: 'No Services', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'INA001', fin: 'Haycock Attorneys  Ina Meyer', trk: 'HAYCOCK ATTORNEYS  INA MEYER', dd: 'HAYCOCK ATT (INA MEYER)', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'HER001', fin: 'Hernus Coetzee Attorneys', trk: 'HERNUS COETZEE ATTORNEYS', dd: 'HERNUS COETZEE ATTORNEYS', status: 'Priority', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'HET001', fin: 'Hettie Van Schalkwyk Attorneys', trk: 'HETTIE VAN SCHALKWYK ATTORNEYS', dd: 'HETTIE VAN SCHALKWYK ATTORNEY', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'HEY001', fin: 'Heyman Attorneys', trk: 'HEYMAN ATTORNEYS', dd: 'HEYMAN', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'HIL002', fin: 'Hill Mchardy & Herbst Inc', trk: 'HILL MCHARDY & HERBST INC', dd: 'HILL MCHARDY & HERBST', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'HIL004', fin: 'Hills Incorporated', trk: 'HILLS INCORPORATED', dd: '', status: 'Dormant', stm: 'COLEEN', inv: 'DORMANT', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'HJB001', fin: 'HJ Booysen Attorneys Inc', trk: 'HJ BOOYSEN ATTORNEYS INC', dd: 'HJ BOOYSEN ATTORNEYS INC', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'HON001', fin: 'Honey Attorneys (Buchner)', trk: 'HONEY ATTORNEYS (BUCHNER)', dd: 'HONEY BUCHNER', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'HON002', fin: 'Honey Attorneys (Prinsloo)', trk: 'HONEY ATTORNEYS (PRINSLOO)', dd: 'HONEY PRINSLOO', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'HON003', fin: 'Honey Attorneys (Vosloo) (Joubert)', trk: 'HONEY ATTORNEYS (VOSLOO) (JOUBERT)', dd: 'HONEY VOSLOO', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'HOR001', fin: 'Horn & Van Rensburg Attorneys', trk: 'HORN & VAN RENSBURG ATTORNEYS', dd: 'HORN & VAN RENSBURG', status: 'No Services', stm: 'DINERO', inv: 'ANGEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'HAB001', fin: 'Hough & Bremner', trk: 'HOUGH & BREMNER', dd: 'HOUGH & BREMNER', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'HPB001', fin: 'HP Buthelezi Inc', trk: 'HP BUTHELEZI INC', dd: 'HP BUTHELEZI INC', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'HTA001', fin: 'Huawei Technologies Africa (Pty) LTD', trk: 'HUAWEI TECHNOLOGIES AFRICA (PTY) LTD', dd: 'HUAWEI TECHNOLOGIES AFRICA', status: 'Pre-bookings Payment', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'HSI001', fin: 'Hurter Spies Inc', trk: 'HURTER SPIES INC', dd: 'HURTER SPIES INC', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'HWT001', fin: 'HW Theron Inc', trk: 'HW THERON INC', dd: 'HW THERON', status: 'Priority', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'IMA001', fin: 'I Mabunda Attorneys', trk: 'I MABUNDA ATTORNEYS', dd: 'I MABUNDA ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'IIM001', fin: 'I.I Myeni Attorneys Inc', trk: 'I.I MYENI ATTORNEYS INC', dd: 'I.I MYENI ATTORNEYS INC', status: 'Pre-Booking', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'ICC001', fin: 'IC Clark Inc', trk: 'IC CLARK', dd: 'IC CLARK', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'IVA001', fin: 'Ivan Maitin Attorneys Incorporated', trk: 'IVAN MAITIN ATTORNEYS INCORPORATED', dd: 'IVAN MAITIN ATTORNEYS INCORPORATED', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'IZA001', fin: 'Izak Croukamp Attorneys', trk: 'IZAK CROUKAMP ATTORNEYS', dd: 'IZAK CROUCAMP', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'JTE001', fin: 'J Temba & Associates', trk: 'J TEMBA & ASSOCIATES', dd: 'J TEMBA & ASSOCIATES', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'JWO001', fin: 'J Wolmarans Inc', trk: 'J WOLMARANS INC', dd: 'J WOLMARANS INC', status: 'Dormant', stm: 'DORMANT', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'HIL001', fin: 'Jaco Visser Attorneys / Hills', trk: 'JACO VISSER ATTORNEYS / HILLS', dd: 'JACO VISSER / HILLS', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'JAC002', fin: 'Jacobus Attorneys', trk: 'JACOBUS ATTORNEYS', dd: 'JACOBUS ATTORNEYS', status: 'No Services', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'JAR002', fin: 'Jarvis Jacobs Raubenheimer Incorporated', trk: 'JARVIS JACOBS RAUBENHEIMER INCORPORATED', dd: 'JARVIS JACOBS RAUBENHEIMER INC', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'JAZ001', fin: 'Jazbhay & Harrichand Attorneys', trk: 'JAZBHAY & HARRICHAND ATTORNEYS', dd: 'JAZBHAY & HARRICHAND ATTORNEYS', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'JEA001', fin: 'Jean Keyser Attorneys', trk: 'JEAN KEYSER ATTORNEYS', dd: 'JEAN KEYSER', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'JER001', fin: 'Jerry Nkeli & Associates Inc', trk: 'JERRY NKELI & ASSOCIATES INC', dd: 'JERRY NKELI & ASSOCIATES INC', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'JHS001', fin: 'JHS Attorneys', trk: 'JHS ATTORNEYS', dd: 'JHS ATTORNEYS (JAN HARM SCHUTTE)', status: 'Priority', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'JFT001', fin: 'Joanne Fitzhenry Attorneys Incorporated', trk: 'JOANNE FITZHENRY ATTORNEYS INCORPORATED', dd: 'J FITZHENRY ATTORNEYS INC', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'JAC001', fin: 'Johan Calitz Attorney Incorporated', trk: 'JOHAN CALITZ ATTORNEY INC', dd: 'JOHAN CALITZ ATTORNEY INC', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'JOU002', fin: 'Joubert Botha', trk: 'JOUBERT BOTHA', dd: 'JOUBERT BOTHA', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'JOU001', fin: 'Joubert Scholtz Incorporated', trk: 'JOUBERT SCHOLTZ INCORPORATED', dd: 'JOUBERT SCHOLTZ INC', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'JSM001', fin: 'JS Mathibela Attorneys', trk: 'JS MATHIBELA ATTORNEYS', dd: 'JS MATHIBELA', status: 'No Services', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'JTL001', fin: 'JT Leso Inc Attorney', trk: 'JT LESO INC ATTORNEY', dd: 'JT LESO INC ATTORNEY', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'JUL001', fin: 'Julyan Attorneys Inc', trk: 'JULYAN ATTORNEYS INC', dd: 'JULYAN ATTORNEYS INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'KBV001', fin: 'KBVS ATTORNEYS', trk: 'KBVS ATTORNEYS', dd: 'KBVS ATTORNEYS', status: 'Priority', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'KEM002', fin: 'KE Modiba Attorneys', trk: 'KE MODIBA ATTORNEYS', dd: 'KE MODIBA ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'NOBUHLE', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'KEL001', fin: 'Keleku Attorneys', trk: 'KELEKU ATTORNEYS', dd: 'KELEKU', status: 'Priority', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'KET001', fin: 'Ketterer Attorneys', trk: 'KETTERER ATTORNEYS', dd: 'KETTERER', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'KDA001', fin: 'Kgadima Kekana Attorneys', trk: 'KGADIMA KEKANA ATTORNEYS', dd: 'KGADIMA KEKANA', status: 'No Services', stm: 'DINERO', inv: 'NOBUHLE', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'KHA001', fin: 'Khanyisa Mogale Attorneys', trk: 'KHANYISA MOGALE ATTORNEYS', dd: 'KHANYISA MOGALE ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'KLI001', fin: 'Klinkenberg Inc Attorneys', trk: 'KLINKENBERG INC ATTORNEYS', dd: 'KLINKENBERG INC', status: 'No Services', stm: '', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'KCA001', fin: 'Kooben Chetty and Associates', trk: 'KOOBEN CHETTY & ASSOCIATES', dd: 'KOOBEN CHETTY & ASSOCIATES', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'KOT001', fin: 'Kotlolo Attorneys', trk: 'KOTLOLO ATTORNEYS', dd: 'KOTLOLO ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'KRU005', fin: 'Kruger and Bender', trk: 'KRUGER AND BENDER', dd: 'KRUGER AND BENDER', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'KRU006', fin: 'Kruger and Company', trk: 'KRUGER & CO', dd: 'KRUGER & CO', status: 'No Services', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'KPA001', fin: 'Kruger Pottinger Attorneys', trk: 'KRUGER POTTINGER ATTORNEYS', dd: 'KRUGER AND POTTINGER ATTORNEYS', status: 'Priority', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'KRU003', fin: 'Kruger Venter Inc', trk: 'KRUGER VENTER INC', dd: 'KRUGER VENTER INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'KUN002', fin: 'Kunene Mangope Inc', trk: 'KUNENE MANGOPE INC', dd: 'KUNENE MANGOPE INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'LMA001', fin: 'L Mapisa Attorneys Inc', trk: 'L MAPISA ATTORNEYS INC', dd: 'L MAPISA ATTORNEYS INC', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'LEI001', fin: 'Leigh De Souza Attorneys & Mediators', trk: 'LEIGH DE SOUZA ATTORNEYS & MEDIATORS', dd: 'LEIGH DE SOUZA ATTORNEYS & MEDIATORS', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'LES002', fin: 'Lessing Heyns & Van der Bank Attorneys', trk: 'LESSING HEYNS & VAN DER BANK ATTORNEYS', dd: 'LESSING HEYNS & VAN DER BANK ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'LEV001', fin: 'Levin Tatanis Inc', trk: 'LEVIN TATANIS INC', dd: 'LEVIN TATANIS INC', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'LHL1MF', fin: 'LHL Attorneys Incorporated', trk: 'LHL ATTORNEYS INCORPORATED', dd: 'LHL ATTORNEYS', status: 'Financed (Other)', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'LIO001', fin: 'Lionel Miller Attorneys', trk: 'LIONEL MILLER ATTORNEYS', dd: 'LIONEL MILLER', status: 'Priority', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'LOM003', fin: 'Lombard And Kriek', trk: 'LOMBARD AND KRIEK', dd: 'LOMBARD AND KRIEK ATTORNEYS', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'LOM002', fin: 'Lombard And Kriek Incorporated', trk: 'LOMBARD AND KRIEK INCORPORATED', dd: 'LOMBARD AND KRIEK INCORPORATED', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'LOM001', fin: 'Lombard Muller & Vennote', trk: 'LOMBARD MULLER & VENNOTE', dd: 'LOMBARD MULLER & VENNOTE', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MGA001', fin: 'M Grobler Attorneys Inc', trk: 'M GROBLER ATTORNEYS INCORPORATED', dd: 'M GROBLER ATTORNEYS INC', status: 'Password Protect', stm: 'DORMANT', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MLR001', fin: 'Maartens Le Roux Inc', trk: 'MAARTENS LE ROUX INC', dd: 'MAARTENS LE ROUX INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MAB002', fin: 'Mabotja Attorneys', trk: 'MABOTJA ATTORNEYS', dd: 'MABOTJA ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'GAVIN', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MAC003', fin: 'MacRobert Attorneys', trk: 'MACROBERT ATTORNEYS', dd: 'MACROBERT ATTORNEYS', status: 'Priority', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'MAG002', fin: 'Magadla Attorneys Inc', trk: 'MAGADLA ATTORNEYS INC', dd: 'MAGADLA ATTORNEYS', status: 'No Services', stm: 'SNOTHILE', inv: 'CHANTEL', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'MAH005', fin: 'Mahumani BM Attorneys Inc', trk: 'MAHUMANI BM ATTORNEYS INC', dd: 'MAHUMANI BM ATTORNEYS INC', status: 'No Services', stm: 'PENDING', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MAJ002', fin: 'Majali Gwabeni Attorneys Inc', trk: 'MAJALI GWABENI ATTORNEYS INC', dd: 'MAJALI GWABENI ATTORNEYS INC', status: 'Dormant', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MAK001', fin: 'Makokga Sebei Attorneys', trk: 'MAKOKGA SEBEI ATTORNEYS', dd: 'MAKOKGA SEBEI', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MAK004', fin: 'Makuse Attorneys', trk: 'MAKUSE ATTORNEYS', dd: 'MAKUSE ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'NOBUHLE', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MAL002', fin: 'Malahlela Attorneys', trk: 'MALAHLELA ATTORNEYS', dd: 'MALAHLELA ATTORNEYS', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MMA003', fin: 'Malebo Mahlobogoane Attorneys Inc', trk: 'MALEBO MAHLOBOGOANE ATTORNEYS INC', dd: 'MALEBO MAHLOBOGOANE ATTORNEYS INC', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'MAL004', fin: 'Malebye Motaung Mtembu Inc', trk: 'MALEBYE MOTAUNG MTEMBU INC', dd: 'MALEBYE MOTAUNG MTEMBU INC', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MAP001', fin: 'Maphaha Attorneys', trk: 'MAPHAHA ATTORNEYS', dd: 'MAPHAHA ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MAR008', fin: 'Maritz Smith Attorneys - Courtroom Finance', trk: 'MARITZ SMITH INC ATTORNEYS - COURTROOM FINANCE AND CONSULTING (PTY) LTD', dd: 'MARITZ SMITH ATTORNEYS  - COURTROOM FINANCE AND CONSULTING (PTY) LTD', status: 'No Services', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'MMA002', fin: 'Marlin Marimuthu Attorneys', trk: 'MARLIN MARIMUTHU ATTORNEYS', dd: 'MARLIN MARIMUTHU ATTORNEYS', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MAS006', fin: 'Masando and Associates Inc', trk: 'MASONDO AND ASSOCIATES INC', dd: 'MASANDO & ASSOCIATES INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MAS001', fin: 'Masweneng Attorneys', trk: 'MASWENENG ATTORNEYS', dd: 'MASWENENG ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MAT004', fin: 'Mateta Attorneys', trk: 'MATETA ATTORNEYS', dd: 'MATETA ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MAT008', fin: 'Mathada & Associates Inc', trk: 'MATHADA & ASSOCIATES', dd: 'MATHADA & ASSOCIATES', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MAT002', fin: 'Mathye KQ Attorneys', trk: 'MATHYE KQ ATTORNEYS', dd: 'MATHYE KQ ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MAV001', fin: 'Mavuya Attorneys Inc', trk: 'MAVUYA ATTORNEYS INC', dd: 'MAVUYA ATTORNEYS INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MAB001', fin: 'MB Mabunda Inc', trk: 'MB MABUNDA INC', dd: '', status: 'Dormant', stm: 'COLEEN', inv: 'DORMANT', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'MBA001', fin: 'Mbambo Attorneys', trk: 'MBAMBO ATTORNEYS', dd: 'MBAMBO', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MCM001', fin: 'Mcmillan Attorneys', trk: 'MCMILLAN ATTORNEYS', dd: 'MCMILLIAN', status: 'Handed-Over', stm: 'FRANK', inv: 'DORMANT', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MEH001', fin: 'ME Hloka Attorneys', trk: 'M.E. HLOKA ATTORNEYS', dd: 'M.E. HLOKA ATTORNEYS', status: 'Priority', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MED001', fin: 'MED Attorneys', trk: 'MED ATTORNEYS', dd: 'MED ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MEI001', fin: 'Meijer Attorneys', trk: 'MEIJER ATTORNEYS', dd: '', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'MEM001', fin: 'Memela Attorneys', trk: 'MEMELA ATTORNEYS', dd: 'MEMELA ATTORNEYS', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'MGI001', fin: 'Mgiba J Attorneys Inc', trk: 'MGIBA J ATTORNEYS INC', dd: 'MGIBA J ATTORNEYS INC.', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MIL003', fin: 'Miller Bosman Le Roux Attorneys', trk: 'MILLER BOSMAN LE ROUX ATTORNEYS', dd: 'MILLER BOSMAN LE ROUX ATTORNEYS', status: '', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'NMM001', fin: 'MKB Attorneys', trk: 'MKB ATTORNEYS', dd: 'MKB ATTORNEYS', status: 'Priority', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'MKE001', fin: 'Mketsu & Associates', trk: 'MKETSU & ASSOCIATES', dd: 'MKETSU & ASSOCIATES', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MOD001', fin: 'Modzuka Inc', trk: 'MODZUKA INC', dd: 'MODZUKA', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'MOG001', fin: 'Mogale Sekgala Attorneys', trk: 'MOGALE SEKGALA ATTORNEYS', dd: 'MOGALE SEKGALA ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MOL003', fin: 'Molefakgotla Attorneys Inc', trk: 'MOLEFAKGOTLA ATTORNEYS INC', dd: 'MOLEFAKGOTLA ATTORNEYS INC', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MOL001', fin: 'Molefe Knight Attorneys', trk: 'MOLEFE KNIGHT ATTORNEYS', dd: 'MOLEFE KNIGHT ATTORNEYS', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'MOL002', fin: 'Molobi Incorporated', trk: 'MOLOBI INCORPORATED', dd: 'MOLOBI INCORPORATED ATTORNEYS', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MOP001', fin: 'Mopeli Attorneys', trk: 'MOPELI ATTORNEYS', dd: 'MOPELI ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'ANGEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'MOS001', fin: 'Moss and Associates Incorporated', trk: 'MOSS AND ASSOCIATES INCORPORATED', dd: 'MOSS AND ASSOCIATES', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'MOT003', fin: 'Motsai Attorneys', trk: 'MOTSAI ATTORNEYS', dd: 'MOTSAI ATTORNEYS', status: 'No Services', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MOT002', fin: 'Motsekuoa Inc Attorneys', trk: 'MOTSEKUOA INC ATTORNEYS', dd: 'MOTSEKUOA INC ATTORNEYS', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'MOU001', fin: 'Mouton & Williams Attorneys', trk: 'MOUTON & WILLIAMS ATTORNEYS', dd: 'MOUTON & WILLIAMS', status: 'No Services', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'MQW001', fin: 'Mqwishi A Attorneys Inc', trk: 'MQWISHI ATTORNEYS', dd: 'MQWISHI ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MTH001', fin: 'Mthombeni & Ramaboea Incorporated', trk: 'MTHOMBENI & RAMABOEA INCORPORATED', dd: 'MTHOMBENI AND RAMABOEA ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'MSI001', fin: 'Mtshali and Shishi Inc Attorneys', trk: 'MTSHALI AND SISHI INC', dd: 'MTSHALI AND SISHI INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'NVD001', fin: 'N Van Der Walt Inc', trk: 'N VAN DER WALT INC', dd: 'N VAN DER WALT INC', status: 'Priority', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'NCL001', fin: 'NC Legal Cost Consultants Pty Ltd', trk: 'NC LEGAL COST CONSULTANTS PTY LTD', dd: 'NC LEGAL COST CONSULTANTS', status: 'Password Protect', stm: 'CHANTEL', inv: 'CHANTEL', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'NDO001', fin: 'Ndobela and Associates', trk: 'NDOBELA AND ASSOCIATES', dd: 'NDOBELA AND ASSOCIATES INCORPORATED', status: 'No Services', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'NEL004', fin: 'Nel and De Wet Inc', trk: 'NEL AND DE WET INC', dd: 'NEL AND DE WET INC', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'NVS001', fin: 'Nel Van Der Merwe & Smalman Inc', trk: 'NEL VAN DER MERWE & SMALMAN INC', dd: 'NEL VAN DER MERWE & SMALMAN INC', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'NEL003', fin: 'Nell Kotze & Van Dyk', trk: 'NELL KOTZE & VAN DYK', dd: 'NELL KOTZE & VAN DYK', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'NER001', fin: 'Nerina Wessels Attorneys', trk: 'NERINA WESSELS ATTORNEYS', dd: 'NERINA WESSELS ATTORNEYS', status: 'No Services', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'NGO002', fin: 'Ngobeni Wiseman Inc Attorneys', trk: 'NGOBENI WISEMAN INC ATTORNEYS', dd: 'NGOBENI WISEMAN INC', status: 'No Services', stm: 'DINERO', inv: 'NOBUHLE', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'NKY001', fin: 'NKelly Incorporated', trk: 'NKELLY INCORPORATED', dd: '', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'NKO001', fin: 'Nkosi Sabelo Attorneys', trk: 'NKOSI SABELO ATTORNEYS', dd: 'NKOSI SABELO ATTORNEYS', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'NOT001', fin: 'Nothnagel Attorneys', trk: 'NOTHNAGEL ATTORNEYS', dd: 'NOTHNAGEL ATTORNEYS', status: 'Handed-Over', stm: 'FRANK', inv: 'EVAH', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'NZI001', fin: 'Nzima Inc', trk: 'NZIMA INC', dd: 'NZIMA INC', status: 'No Services', stm: 'DINERO', inv: 'ANGEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'NZU001', fin: 'Nzunza Attorneys (Verdant Law)', trk: 'NZUNZA ATTORNEYS', dd: 'NZUNZA ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'OEL001', fin: 'Oelofse CJP Att / Legal Wise', trk: 'OELOFSE CJP ATT / LEGAL WISE', dd: 'OELOFSE CJP ATT / LEGAL WISE', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'OEL002', fin: 'Oelofse CJP Att / Scorpion', trk: 'CJP OELOFSE ATTORNEYS', dd: 'OELOFSE CJP ATT / SCORPION', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'PAT003', fin: 'Pat Naidoo Attorneys', trk: 'PAT NAIDOO ATTORNEYS', dd: 'PAT NAIDOO ATTORNEYS', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'PAT002', fin: 'Pather and Pather Attorneys', trk: 'PATHER AND PATHER ATTORNEYS', dd: 'PATHER AND PATHER ATTORNEYS', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'PAT004', fin: 'Patterson Breytenbach Inc', trk: 'PATTERSON BREYTENBACH INC', dd: 'PATTERSON BREYTENBACH INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'PEY002', fin: 'Peyper And Botha Attorneys Incorporated', trk: 'PEYPER AND BOTHA ATTORNEYS INCORPORATED', dd: 'PEYPER AND BOTHA ATTORNEYS INCORPORATED', status: 'No Services', stm: 'LORATO', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'PHA001', fin: 'Phatshoane Henney Attorneys', trk: 'PHATSHOANE HENNEY ATTORNEYS', dd: 'PHATSHOANE HENNEY', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'PCI001', fin: 'Phindela Chithi Inc', trk: 'PHINDELA CHITHI INCORPORATED', dd: 'PHINDELA CHITHI INCORPORATED', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'PIET01', fin: 'Pieter Skein Attorneys', trk: 'PIETER SKEIN ATTORNEYS', dd: 'PIETER SKEIN', status: 'No Services', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'PIE001', fin: 'Pieter W De Wet Attorneys', trk: 'PIETER W DE WET ATTORNEYS', dd: 'PIETER DE WET', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'PML001', fin: 'PM Law Inc', trk: 'PM LAW INC', dd: 'PM LAW INC', status: 'No Services', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'POD001', fin: 'Podbielski Inc Attorneys', trk: 'PODBIELSKI INC ATTORNEYS', dd: 'PODBIELSKI INC ATTORNEYS', status: 'No Services', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'POT003', fin: 'Potgieter Beeken Attorneys', trk: 'POTGIETER BEEKEN ATTORNEYS', dd: 'POTGIETER BEEKEN', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'POT004', fin: 'Potgieter Inc', trk: 'POTGIETER INC', dd: 'POTGIETER INCORPORATED', status: 'No Services', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'POT002', fin: 'Potgieter R Attorneys', trk: 'POTGIETER R ATTORNEYS', dd: 'POTGIETER R ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'PRE002', fin: 'Pretorius Attorneys Inc', trk: 'PRETORIUS ATTORNEYS INC', dd: 'PRETORIUS', status: 'Priority', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'RAB001', fin: 'Rabia Sayed Attorneys', trk: 'RABIA SAYED ATTORNEYS', dd: 'RABIA SAYED', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'RBA001', fin: 'Rabie Botha And Associates', trk: 'RABIE BOTHA AND ASSOCIATES', dd: 'RABIE BOTHA AND ASSOCIATES', status: 'No Services', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'RMA001', fin: 'Rabora Mulele Attorneys', trk: 'RABORA MULELE ATTORNEYS', dd: 'RABORA MULELE ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'RAM004', fin: 'Ramaesele Mphahlele Attorneys', trk: 'RAMAESELE MPHAHLELE ATTORNEYS', dd: 'RAMAESELE MPHAHLELE ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'RAM002', fin: 'Ramakgwakgwa Attorneys', trk: 'RAMAKGWAKGWA ATTORNEYS', dd: 'RAMAKGWAKGWA', status: 'No Services', stm: 'DINERO', inv: 'NOBUHLE', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'RDS001', fin: 'Raphael David Smith', trk: 'RAPHAEL DAVID SMITH', dd: 'RAPHAEL DAVID SMITH', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'RDP001', fin: 'RDP Attorneys (Ruarc Dhabi Pillay)', trk: 'RDP ATTORNEYS (RUARC DHABI PILLAY)', dd: 'RDP ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'GAVIN', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'RFI001', fin: 'Rene Fouche Inc', trk: 'RENE FOUCHE INC', dd: 'RENE FOUCHE INC', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'RES001', fin: 'Reshoketswe Mmolawa Attorneys', trk: 'RESHOKETSWE MMOLAWA ATTORNEYS', dd: 'RESHOKETSWE MMOLAWA ATTORNEYS', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'RHL001', fin: 'RH Lawyers Incorporated', trk: 'RH LAWYERS INCORPORATED', dd: 'RH LAWYERS INCORPORATED', status: 'Financed (Other)', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'RHK001', fin: 'RHK Attorneys at Law', trk: 'RHK ATTORNEYS INCORPORATED', dd: 'RHK ATTORNEYS AT LAW', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'RIC002', fin: 'Richard Spoor Incorporated', trk: 'RICHARD SPOOR INCORPORATED', dd: 'RICHARD SPOOR INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'RIC001', fin: 'Richards & Palmer Inc', trk: 'RICHARDS & PALMER INC', dd: 'RICHARDS & PALMER ATTORNEYS', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'RMS001', fin: 'RM Masina Attorneys', trk: 'RM MASINA ATTORNEYS', dd: 'RM MASINA', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'ROB003', fin: 'Roberts & Associates', trk: 'ROBERTS AND ASSOCIATES INC', dd: 'ROBERTS & ASSOCIATES INC', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ROO002', fin: 'Rooseboom Attorneys', trk: 'ROOSEBOOM ATTORNEYS', dd: 'ROOSEBOOM ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'ROU002', fin: 'Roux Van Vuuren Attorneys', trk: 'ROUX VAN VUUREN ATTORNEYS', dd: 'ROUX VAN VUUREN', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'RCA001', fin: 'Rupert Candy Attorneys Inc', trk: 'RUPERT CANDY ATTORNEYS INC.', dd: 'RUPERT CANDY ATTORNEYS INCORPORATED', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'RWA001', fin: 'RW Africa Attorneys', trk: 'RW AFRICA ATTORNEYS', dd: 'RW AFRICA ATTORNEYS', status: 'No Services', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'SMO001', fin: 'S Mohammed Inc', trk: 'S MOHAMMED INC', dd: 'S MOHAMMED INC', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'SND001', fin: 'S Ndlela Attorneys Inc', trk: 'S NDLELA ATTORNEYS', dd: 'S NDLELA ATTORNEYS INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SSI002', fin: 'S Simayile Attorneys Inc', trk: 'S SIMAYILE ATTORNEYS INC', dd: 'S SIMAYILE ATTORNEYS INC', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'STE014', fin: 'S Steyn Inc (Schumanns)', trk: 'S STEYN INCORPORATED (SCHUMANNS)', dd: 'S STEYN INCORPORATED (SCHUMANNS)', status: 'Financed (Other)', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'STE004', fin: 'S Steyn Incorporated', trk: 'S STEYN INCORPORATED', dd: 'S STEYN INCORPORATED', status: 'Financed (Other)', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'STE005', fin: 'S Steyn Incorporated (Nothnagel)', trk: 'S STEYN INCORPORATED (NOTHNAGEL)', dd: 'S STEYN INCORPORATED (NOTHNAGEL)', status: 'Financed (Other)', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'SAT001', fin: 'SA Telelo Attorneys', trk: 'SA TELELO ATTORNEYS', dd: 'SA TELELO ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'SAL003', fin: 'Sal Govender and Associates', trk: 'SAL GOVENDER & ASSOCIATES', dd: 'SAL GOVENDOR & ASSOCIATES', status: 'Priority', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SAV001', fin: 'Savage Jooste And Adams Attorneys', trk: 'SAVAGE JOOSTE AND ADAMS ATTORNEYS', dd: 'SAVAGE JOOSTE AND ADAMS ATTORNEYS', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SBG001', fin: 'Schoones Belling & Georgiev Attorneys', trk: 'SCHOONES BELLING & GEORGIEV', dd: 'SCHOONEES BELLING & GEORGIEV', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'SCH001', fin: 'Schumann Van Den Heever & Slabbert Inc', trk: 'SCHUMANN VAN DEN HEEVER & SLABBERT INC', dd: 'SCHUMANN VAN DEN HEEVER', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'SCH005', fin: 'Schutte Inc', trk: 'SCHUTTE INC', dd: 'SCHUTTE INC', status: 'No Services', stm: 'COLEEN', inv: 'CHANTEL', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'SCO001', fin: 'Scott Els Attorneys Incorporated', trk: 'SCOTT ELS ATTORNEYS INCORPORATED', dd: 'SCOTT ELS ATTORNEYS INCORPORATED', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'SMA001', fin: 'SD Moloi & Associates Incorporated', trk: 'SD MOLOI & ASSOCIATES INCORPORATED', dd: 'SD MOLOI & ASSOCIATES', status: 'No Services', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SEF001', fin: 'Seffore Attorneys', trk: 'SEFFORE ATTORNEYS', dd: 'SEFFORE ATTORNEYS', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SEL001', fin: 'Selamolela Inc', trk: 'SELAMOLELA INC', dd: 'SELAMOLELA INC', status: 'Password Protect', stm: 'DINERO', inv: 'NOBUHLE', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'SEP001', fin: 'Selepe KR Attorneys', trk: 'SELEPE KR ATTORNEYS', dd: 'SELEPE KR ATTORNEYS', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'SSL001', fin: 'Sephecholo Lechuti Lesofe Inc', trk: 'SEPHECHOLO LECHUTI LESOFE INC', dd: 'SEPHECHOLO LECHUTI LESOFE INC', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'SER001', fin: 'Serfontein Viljoen Swart', trk: 'SERFONTEIN VILJOEN SWART', dd: 'SERFONTEIN VILJOEN & SWART', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'SER002', fin: 'Serfontein Viljoen Swart - Bronkhorstspruit', trk: 'SERFONTEIN VILJOEN SWART - BRONKHORSTSPRUIT', dd: 'SERFONTEIN VILJOEN SWART - BRONKHORSTSPRUIT', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'SHA001', fin: 'Shaheem Samsodien Attorneys', trk: 'SHAHEEM SAMSODIEN ATTORNEYS', dd: 'SHAHEEM SAMSODIEN ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'SHA004', fin: 'Shai T Attorneys Inc', trk: 'SHAI T ATTORNEYS INC', dd: 'SHAI T ATTORNEYS INC', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'SHA002', fin: 'Shayne White Inc', trk: 'SHAYNE WHITE INC', dd: 'SHAYNE WHITE INC', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'SHI001', fin: 'Shields Attorneys', trk: 'SHIELDS ATTORNEYS', dd: 'SHIELDS ATTORNEYS', status: 'Password Protect', stm: 'DORMANT', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SHI002', fin: 'Shishonge Attorneys Inc', trk: 'SHISHONGE ATTORNEYS INC', dd: 'SHISHONGE ATTORNEYS INC', status: 'Dormant', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'SIM001', fin: 'Simpsons Attorneys Inc', trk: 'SIMPSONS ATTORNEYS INC', dd: 'SIMPSONS ATTORNEYS INC', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SLA002', fin: 'Slabbert & Slabbert Attorneys', trk: 'SLABBERT & SLABBERT ATTORNEYS', dd: 'SLABBERT & SLABBERT ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'SLD001', fin: 'SLDP Attorneys', trk: 'SLDP ATTORNEYS', dd: 'SLDP ATTORNEYS', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'SME001', fin: 'SME Mohai Attorneys', trk: 'SME MOHAI ATTORNEYS', dd: 'SME MOHAI ATTORNEYS', status: 'No Services', stm: 'NOBUHLE', inv: 'MARISKA', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'SLA001', fin: 'Snyman Lotz Inc', trk: 'SNYMAN LOTZ INC', dd: 'SNYMAN LOTZ ATTORNEYS', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'SOH001', fin: 'Sohn And Wood Attorneys', trk: 'SOHN AND WOOD ATTORNEYS', dd: 'SOHN AND WOOD ATTORNEYS', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'SPA001', fin: 'Spangenberg Zietsman & Bloem', trk: 'SPANGENBERG ZIETSMAN & BLOEM', dd: 'SPANGENBERG ZIETSMAN & BLOEM', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'STA003', fin: 'Stander & Associates', trk: 'STANDER & ASSOCIATES', dd: 'STANDER & ASSOCIATES', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'STA002', fin: 'Stander & Partners', trk: 'STANDER & PARTNERS', dd: 'STANDER & PARTNERS', status: '', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'SSI001', fin: 'Steenkamp & Spies Inc', trk: 'STEENKAMP & SPIES INC', dd: 'STEENKAMP & SPIES INC', status: 'Priority', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'STE007', fin: 'Steenkamp Van Niekerk Inc', trk: 'STEENKAMP VAN NIEKERK INC', dd: 'STEENKAMP VAN NIEKERK', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'STE012', fin: 'Stefan Greyling Inc', trk: 'STEFAN GREYLING INC', dd: 'STEFAN GREYLING INC', status: 'Password Protect', stm: 'LORATO', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'SNP001', fin: 'STEVE NKOSI AND PARTNERS', trk: 'STEVE NKOSI AND PARTNERS', dd: 'STEVE NKOSI & PARTNERS', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'SYM001', fin: 'Symington & De Kok', trk: 'SYMINGTON & DE KOK', dd: 'SYMINGTON & DE KOK', status: 'Dormant', stm: 'DORMANT', inv: 'DORMANT', bul: 'DORMANT', bu: 'DORMANT' },
      { acc: 'TCH001', fin: 'T Chabalala Inc', trk: 'T CHABALALA INC', dd: 'T CHABALALA INC', status: 'Password Protect', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'TAI001', fin: 'Taitz & Skikne', trk: 'TAITZ & SKIKNE ATTORNEYS', dd: 'TAITZ & SKIKNE', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'TAU002', fin: 'Taute Bouwer and Cilliers Inc', trk: 'TAUTE BOUWER & CILLIERS INC', dd: 'TAUTE BOUWER & CILLIERS INC', status: 'Password Protect', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'TAY001', fin: 'Taylor Ballack & Co', trk: 'TAYLOR BALLACK & CO', dd: 'TAYLOR BALLACK & CO', status: 'Pre-booking Payment', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'TEN001', fin: 'Tengwa Attorneys', trk: 'TENGWA ATTORNEYS', dd: 'TENGWA ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'CHANTEL', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'THO002', fin: 'Thorrington Smith and Silver', trk: 'THORRINGTON SMITH AND SILVER', dd: 'THORRINGTON SMITH AND SILVER', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'THU001', fin: 'Thulo Tt Attorneys', trk: 'THULO TT ATTORNEYS', dd: 'THULO TT ATTORNEYS', status: 'No Services', stm: 'DINERO', inv: 'NOBUHLE', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'TSA002', fin: 'Tiaan Smuts Attorneys', trk: 'TIAAN SMUTS ATTORNEYS', dd: 'TIAAN SMUTS INC ATTORNEY', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'TIA001', fin: 'Tiandi Du Plessis', trk: 'TIANDI DU PLESSIS', dd: 'TIANDI DU PLESSIS', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'TNR001', fin: 'TN Ramollo Attorneys Inc', trk: 'TN RAMOLLO ATTORNEYS INC', dd: 'TN RAMOLLO ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'TPK001', fin: 'TP Khoza Attorneys', trk: 'TP KHOZA ATTORNEYS', dd: 'TP KHOZA ATTORNEYS', status: 'Password Protect', stm: 'SNOTHILE', inv: 'CHANTEL', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'TSM001', fin: 'TS Makhubela Att Inc', trk: 'TS MAKHUBELA ATTORNEYS', dd: 'TS MAKHUBELA ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'TBM001', fin: 'Tshegofatso Beverly Modisane', trk: 'TSHEGOFATSO BEVERLY MODISANE', dd: '', status: 'No Services', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'TSO001', fin: 'Tsoku Chueu Inc Attorneys', trk: 'TSOKU CHUEU INC ATTORNEYS', dd: 'TSOKU CHUEU INC ATTORNEYS', status: 'No Services', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'TSU001', fin: 'Tsuela Attorneys', trk: 'TSUELA ATTORNEYS', dd: 'TSUELA ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'TUC001', fin: 'Tuckers Incorporated', trk: 'TUCKERS INCORPORATED', dd: 'TUCKERS ATTORNEYS', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'UYS001', fin: 'Uys Jordaan Attorneys', trk: 'UYS JORDAAN ATTORNEYS', dd: 'UYS JORDAAN ATTORNEYS', status: 'Password Protect', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'VAN013', fin: 'Van Blerk Attorneys Inc', trk: 'VAN BLERK ATTORNEYS INC', dd: 'VAN BLERK ATTORNEYS INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'VAN002', fin: 'Van Der Elst Attorneys', trk: 'VAN DER ELST ATTORNEYS', dd: 'VAN DER ELST', status: 'No Services', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'VAN006', fin: 'Van der Spuy Attorneys', trk: 'VAN DER SPUY ATTORNEYS', dd: 'VAN DER SPUY', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'VAN010', fin: 'Van Heerden & Associates Attorneys', trk: 'VAN HEERDEN & ASSOCIATES ATTORNEYS', dd: 'VAN HEERDEN & ASSOCIATES ATTORNEYS', status: 'No Services', stm: 'CHANTEL', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'VAN007', fin: 'Van Niekerk', trk: 'VAN NIEKERK ATTORNEYS', dd: 'VAN NIEKERK', status: 'No Services', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Jacques Erasmus', bu: 'SISONKE - DURAN' },
      { acc: 'HEE001', fin: 'Van Wyk Van Heerden Attorneys', trk: 'VAN WYK VAN HEERDEN ATTORNEYS', dd: 'VAN WYK VAN HEERDEN ATTORNEYS', status: 'Dormant', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'VAN001', fin: 'Van Zyl Le Roux Attorneys', trk: 'VAN ZYL LE ROUX ATTORNEYS', dd: 'VAN ZYL LE ROUX', status: 'Priority', stm: 'LEONARD/BANELE', inv: 'KAVISHA', bul: 'Leonard Murugan', bu: 'KUTLWANO - LEONARD' },
      { acc: 'VDN001', fin: 'VDN Attorneys Inc', trk: 'VDN ATTORNEYS INC', dd: 'VDN ATTORNEYS INC', status: 'Dormant', stm: 'NOBUHLE', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'VEN002', fin: 'Venters Incorporated', trk: 'VENTERS INCORPORATED', dd: 'VENTERS INC', status: 'No Services', stm: 'LORATO', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'VEN003', fin: 'Venters Rust Incorporated', trk: 'VENTERS RUST INCORPORATED', dd: 'VENTERS RUST ATTORNEYS INC', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'VOR001', fin: 'Vorster & Brandt', trk: 'VORSTER & BRANDT', dd: 'VORSTER & BRANDT', status: 'Password Protect', stm: 'ROWAN', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'WEB001', fin: 'WEBBERS ATTORNEYS', trk: 'WEBBERS ATTORNEYS', dd: 'WEBBERS ATTORNEYS', status: 'No Services', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'WEH001', fin: 'Wehmeyers Attorneys', trk: 'WEHMEYERS ATTORNEYS', dd: 'WEHMEYERS', status: 'Priority', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'WER002', fin: 'Werner Boshoff Inc', trk: 'WERNER BOSHOFF INCORPORATED', dd: 'WERNER BOSHOFF ATTORNEYS', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'WER001', fin: 'Werner Vermaak Attorneys', trk: 'WERNER VERMAAK ATTORNEYS', dd: 'WERNER VERMAAK', status: 'No Services', stm: 'BANELE', inv: 'ROWAN', bul: 'George Viljoen', bu: 'NASIRA - DYLAN' },
      { acc: 'WPA001', fin: 'Wilna Pottinger Attorneys', trk: 'WILNA POTTINGER ATTORNEYS', dd: 'WILNA POTTINGER ATTORNEYS', status: 'Password Protect', stm: 'MARISKA', inv: 'NOBUHLE', bul: 'Nthabiseng Kgomo', bu: 'KOPANO - NTHABI' },
      { acc: 'WIM001', fin: 'Wim Krynauw Incorporated', trk: 'WIM KRYNAUW INCORPORATED', dd: 'WIM KRYNAUW ATTORNEYS INC', status: 'Password Protect', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'WJC001', fin: 'WJ Coetzer Attorneys', trk: 'WJ COETZER ATTORNEYS', dd: 'WJ COETZER ATTORNEYS INC', status: 'Password Protect', stm: 'SNOTHILE', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'YSA001', fin: 'Youveka Sunkur Attorneys Inc', trk: 'YOUVEKA SUNKUR ATTORNEYS INC', dd: 'YOUVEKA SUNKUR ATTORNEYS', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'YOZ001', fin: 'Yozi Attorneys', trk: 'YOZI ATTORNEYS INC', dd: 'YOZI ATTORNEYS INC', status: 'Password Protect', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
      { acc: 'ZAN002', fin: 'Zandre Smit Attorneys', trk: 'ZANDRE SMIT ATTORNEYS', dd: 'ZANDRE SMIT ATTORNEYS', status: 'Financed (Other)', stm: 'COLEEN', inv: 'GAVIN', bul: 'Duran Moonsamy', bu: 'SISONKE - DURAN' },
      { acc: 'ZAN001', fin: 'Zane Haneef Attorneys', trk: 'ZANE HANEEF ATTORNEYS', dd: 'ZANE HANEEF ATTORNEYS', status: 'No Services', stm: 'ANGEL', inv: 'ROWAN', bul: 'Dylan Ramos', bu: 'NASIRA - DYLAN' },
    ];

    // Clear existing records
    const existing = await base44.asServiceRole.entities.FirmReference.list();
    for (const rec of existing) {
      await base44.asServiceRole.entities.FirmReference.delete(rec.id);
    }

    // Bulk create matched records
    const records = rawRows.map(r => ({
      x3_account_no: r.acc || '',
      finance_name: r.fin || '',
      tracking_name: r.trk || '',
      dropdown_name: r.dd || '',
      status: r.status || '',
      dc_stm: r.stm || '',
      dc_inv: r.inv || '',
      bul: r.bul || '',
      business_unit: r.bu || '',
      case_administrator: '',
    }));

    await base44.asServiceRole.entities.FirmReference.bulkCreate(records);

    return Response.json({ success: true, imported: records.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});