// Role-based access control configuration
export const ROLE_PERMISSIONS = {
  admin: {
    label: "Admin",
    canAccess: [
      "Dashboard",
      "Analytics",
      "Clients",
      "ClientContacts",
      "Experts",
      "AppointmentTools",
      "Contracts",
      "ExpensesHub",
      "Finance",
      "MessageCentre",
      "FollowUpRules",
      "BULManagement",
      "BULPerformance",
      "CompanyTargets",
      "BULDashboard",
      "FinanceDashboard",
      "FinanceReporting",
      "Marketing",
      "BusinessCard",
      "SocialMedia",
      "Appointments",
      "MeetingMinutes",
      "FollowUps",
      "PricingProposals",
      "EntertainmentProposals",
      "Expenses",
      "Mileage",
      "IntakeForms",
      "UserManagement",
      "Help",
    ],
    canEdit: ["all"],
    canDelete: ["all"],
  },
  sales_manager: {
    label: "Sales Manager",
    canAccess: [
      "Dashboard",
      "Analytics",
      "Clients",
      "ClientContacts",
      "Experts",
      "AppointmentTools",
      "Contracts",
      "ExpensesHub",
      "Finance",
      "MessageCentre",
      "FollowUpRules",
      "BULManagement",
      "BULPerformance",
      "CompanyTargets",
      "BULDashboard",
      "FinanceReporting",
      "Marketing",
      "BusinessCard",
      "SocialMedia",
      "Appointments",
      "MeetingMinutes",
      "FollowUps",
      "PricingProposals",
      "EntertainmentProposals",
      "Expenses",
      "Mileage",
      "IntakeForms",
      "UserManagement",
      "Help",
    ],
    canEdit: ["all"],
    canDelete: ["all"],
  },
  senior_management: {
    label: "Senior Management",
    canAccess: [
      "Dashboard",
      "Analytics",
      "Clients",
      "ClientContacts",
      "Experts",
      "AppointmentTools",
      "Contracts",
      "ExpensesHub",
      "Finance",
      "MessageCentre",
      "FollowUpRules",
      "BULManagement",
      "BULPerformance",
      "CompanyTargets",
      "BULDashboard",
      "FinanceReporting",
      "Marketing",
      "BusinessCard",
      "SocialMedia",
      "Appointments",
      "MeetingMinutes",
      "FollowUps",
      "PricingProposals",
      "EntertainmentProposals",
      "Expenses",
      "Mileage",
      "IntakeForms",
      "UserManagement",
      "Help",
    ],
    canEdit: ["all"],
    canDelete: ["all"],
  },
  bul_manager: {
    label: "BUL Manager",
    canAccess: [
      "Dashboard",
      "Analytics",
      "Clients",
      "ClientContacts",
      "Experts",
      "AppointmentTools",
      "Contracts",
      "ExpensesHub",
      "Finance",
      "MessageCentre",
      "FollowUpRules",
      "BULManagement",
      "BULPerformance",
      "BULDashboard",
      "FinanceReporting",
      "Marketing",
      "BusinessCard",
      "SocialMedia",
      "Appointments",
      "MeetingMinutes",
      "FollowUps",
      "PricingProposals",
      "EntertainmentProposals",
      "Expenses",
      "Mileage",
      "IntakeForms",
      "Help",
    ],
    canEdit: ["targets", "teams", "leave", "clients", "appointments"],
    canDelete: ["own_records"],
    filterRule: "own_bul_data",
  },
  finance_user: {
    label: "Finance User",
    canAccess: [
      "Dashboard",
      "Finance",
      "MessageCentre",
      "FinanceDashboard",
      "FinanceReporting",
      "Help",
    ],
    canEdit: ["statements", "alerts"],
    canDelete: ["none"],
    filterRule: "assigned_firms",
  },
  team_member: {
    label: "Team Member",
    canAccess: [
      "Dashboard",
      "Clients",
      "ClientContacts",
      "Appointments",
      "FollowUps",
      "MeetingMinutes",
      "PricingProposals",
      "MessageCentre",
      "Help",
    ],
    canEdit: ["own_records"],
    canDelete: ["none"],
    filterRule: "own_team_data",
  },
  business_unit_leader: {
    label: "Business Unit Leader",
    canAccess: [
      "Dashboard",
      "Analytics",
      "Clients",
      "ClientContacts",
      "Experts",
      "AppointmentTools",
      "Contracts",
      "ExpensesHub",
      "Finance",
      "MessageCentre",
      "FollowUpRules",
      "BULPerformance",
      "BULDashboard",
      "FinanceReporting",
      "Marketing",
      "BusinessCard",
      "SocialMedia",
      "Appointments",
      "MeetingMinutes",
      "FollowUps",
      "PricingProposals",
      "EntertainmentProposals",
      "Expenses",
      "Mileage",
      "IntakeForms",
      "Help",
    ],
    canEdit: ["clients", "appointments", "follow_ups", "pricing_proposals", "own_records"],
    canDelete: ["own_records"],
    filterRule: "own_bul_clients",
  },
  kac: {
    label: "Key Accounts Consultant",
    canAccess: [
      "Dashboard",
      "Clients",
      "ClientContacts",
      "Experts",
      "AppointmentTools",
      "Contracts",
      "ExpensesHub",
      "Finance",
      "MessageCentre",
      "BULPerformance",
      "BULDashboard",
      "FinanceReporting",
      "Appointments",
      "MeetingMinutes",
      "FollowUps",
      "PricingProposals",
      "EntertainmentProposals",
      "Expenses",
      "Mileage",
      "IntakeForms",
      "Help",
    ],
    canEdit: ["clients", "appointments", "follow_ups", "pricing_proposals", "own_records"],
    canDelete: ["own_records"],
    filterRule: "assigned_clients",
  },
};

export const canAccessPage = (role, pageName) => {
  const permissions = ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.team_member;
  return permissions.canAccess.includes(pageName);
};

export const canEditSection = (role, section) => {
  const permissions = ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.team_member;
  return permissions.canEdit.includes("all") || permissions.canEdit.includes(section);
};

export const canDeleteRecord = (role) => {
  const permissions = ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.team_member;
  return permissions.canDelete.includes("all");
};

export const getFilterRuleForRole = (role) => {
  const permissions = ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.team_member;
  return permissions.filterRule || null;
};