import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { client_name, client_id, matters } = await req.json();

    if (!matters?.length) return Response.json({ error: 'No matters provided' }, { status: 400 });

    // Look up the client to find finance clerk / linked person
    let financeEmail = 'chantel@fundamedical.co.za'; // fallback default
    let financePersonName = 'Finance Team';

    if (client_id || client_name) {
      // Try to find client record
      const clients = client_id
        ? await base44.asServiceRole.entities.Client.filter({ id: client_id })
        : await base44.asServiceRole.entities.Client.filter({ firm_name: client_name });

      const client = clients?.[0];

      if (client?.finance_clerk) {
        // Look up TeamAssignment to get email of this finance person
        const teamMembers = await base44.asServiceRole.entities.TeamAssignment.filter({
          person_name: client.finance_clerk
        });
        if (teamMembers?.[0]?.person_email) {
          financeEmail = teamMembers[0].person_email;
          financePersonName = client.finance_clerk;
        } else {
          // Try FirmReference dc_stm mapping
          const firmRefs = await base44.asServiceRole.entities.FirmReference.filter({
            finance_name: client_name
          });
          if (firmRefs?.[0]?.dc_stm) {
            const dcMembers = await base44.asServiceRole.entities.TeamAssignment.filter({
              person_name: firmRefs[0].dc_stm
            });
            if (dcMembers?.[0]?.person_email) {
              financeEmail = dcMembers[0].person_email;
              financePersonName = firmRefs[0].dc_stm;
            }
          }
        }
      }
    }

    const bulName = user.full_name || user.email;
    const dateStr = new Date().toLocaleDateString('en-ZA', { day: '2-digit', month: 'long', year: 'numeric' });

    // Build HTML table of matters
    const rows = matters.map((m, i) => `
      <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
        <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${m.law_firm || client_name}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${m.law_firm_reference || '-'}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${m.claimant_name || '-'}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${m.total_outstanding || '-'}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;">${m.matter_feedback || '-'}</td>
      </tr>
    `).join('');

    const htmlBody = `
      <div style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;">
        <div style="background:#081F3F;padding:20px;border-radius:8px;margin-bottom:24px;">
          <h2 style="color:#92F21D;margin:0;">FundaMedical — Matter Feedback</h2>
          <p style="color:#34CCD0;margin:8px 0 0;">Submitted by ${bulName} on ${dateStr}</p>
        </div>

        <p style="color:#1e293b;">Hi ${financePersonName},</p>
        <p style="color:#1e293b;">Please find below the matter feedback captured during a visit to <strong>${client_name}</strong>:</p>

        <table style="width:100%;border-collapse:collapse;margin:16px 0;font-size:13px;">
          <thead>
            <tr style="background:#081F3F;">
              <th style="padding:10px 12px;text-align:left;color:#92F21D;font-weight:600;">Law Firm</th>
              <th style="padding:10px 12px;text-align:left;color:#92F21D;font-weight:600;">Law Firm Reference</th>
              <th style="padding:10px 12px;text-align:left;color:#92F21D;font-weight:600;">Claimant Name</th>
              <th style="padding:10px 12px;text-align:left;color:#92F21D;font-weight:600;">Total Outstanding</th>
              <th style="padding:10px 12px;text-align:left;color:#92F21D;font-weight:600;">Matter Feedback</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>

        <p style="color:#64748b;font-size:12px;margin-top:24px;border-top:1px solid #e2e8f0;padding-top:16px;">
          This email was automatically generated by the FundaMedical Sales Hub after a client visit.<br/>
          BU Representative: ${bulName}
        </p>
      </div>
    `;

    // NOTE: Base44 SendEmail can only send to registered app users.
    // We send to the BU (logged-in user) with full finance person details so they can forward,
    // OR if a RESEND_API_KEY secret is set, we send directly to the finance person.
    const resendKey = Deno.env.get('RESEND_API_KEY');

    if (resendKey) {
      // Send directly via Resend
      const payload = {
        from: 'FundaMedical Sales Hub <noreply@fundamedical.co.za>',
        to: [financeEmail],
        cc: ['frank@fundamedical.co.za'],
        subject: `Matter Feedback — ${client_name} — ${dateStr}`,
        html: htmlBody,
      };
      const resendRes = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${resendKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const resendData = await resendRes.json();
      if (!resendRes.ok) throw new Error('Resend error: ' + JSON.stringify(resendData));
      return Response.json({ success: true, sent_to: financeEmail, method: 'resend' });
    } else {
      // Fallback: send to the logged-in BU user (they are an app user)
      const notifyBody = `
        <p>Hi ${bulName},</p>
        <p>Your matter feedback for <strong>${client_name}</strong> has been saved. Please forward this email to <strong>${financePersonName} (${financeEmail})</strong> and CC frank@fundamedical.co.za.</p>
        ${htmlBody}
      `;
      await base44.asServiceRole.integrations.Core.SendEmail({
        to: user.email,
        subject: `[Action Required] Forward to Finance — Matter Feedback: ${client_name}`,
        body: notifyBody,
        from_name: 'FundaMedical Sales Hub',
      });
      return Response.json({ success: true, sent_to: user.email, method: 'forwarded_to_bu', finance_email: financeEmail });
    }
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});