import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { meeting_id, emails } = await req.json();

    if (!meeting_id) return Response.json({ error: 'meeting_id required' }, { status: 400 });

    const meeting = await base44.asServiceRole.entities.MeetingMinutes.get(meeting_id);
    if (!meeting) return Response.json({ error: 'Meeting not found' }, { status: 404 });

    const services = Object.entries(meeting.bu_services || {})
      .filter(([, v]) => v)
      .map(([k]) => k.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()))
      .join(', ');

    const subject = `Meeting Summary: ${meeting.client_name} — ${meeting.date}`;

    const body = `
<html><body style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto;">
  <div style="background: #081F3F; padding: 20px; border-radius: 8px 8px 0 0;">
    <h1 style="color: #92F21D; margin: 0; font-size: 20px;">FundaMedical Meeting Summary</h1>
    <p style="color: #34CCD0; margin: 4px 0 0;">${meeting.client_name} — ${meeting.date}</p>
  </div>
  <div style="border: 1px solid #e0e0e0; border-top: none; padding: 24px; border-radius: 0 0 8px 8px;">
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
      <tr><td style="padding: 6px; color: #666; width: 160px;">Law Firm</td><td style="padding: 6px; font-weight: bold;">${meeting.client_name || '—'}</td></tr>
      <tr style="background:#f9f9f9;"><td style="padding: 6px; color: #666;">Date</td><td style="padding: 6px;">${meeting.date || '—'}</td></tr>
      <tr><td style="padding: 6px; color: #666;">Location</td><td style="padding: 6px;">${meeting.city || '—'}</td></tr>
      <tr style="background:#f9f9f9;"><td style="padding: 6px; color: #666;">FundaMedical Team</td><td style="padding: 6px;">${meeting.attendees || '—'}</td></tr>
      <tr><td style="padding: 6px; color: #666;">Law Firm Reps</td><td style="padding: 6px;">${meeting.law_firm_representatives || '—'}</td></tr>
      <tr style="background:#f9f9f9;"><td style="padding: 6px; color: #666;">Recorded By</td><td style="padding: 6px;">${meeting.recorded_by || '—'}</td></tr>
    </table>

    ${meeting.agenda ? `<h3 style="color: #081F3F; margin-bottom: 8px;">Agenda</h3><p style="background: #f5f5f5; padding: 12px; border-radius: 6px; margin: 0 0 20px;">${meeting.agenda}</p>` : ''}

    ${services ? `<h3 style="color: #081F3F; margin-bottom: 8px;">Services Discussed</h3><p style="background: #e8f5e9; padding: 12px; border-radius: 6px; margin: 0 0 20px; color: #2e7d32;">${services}</p>` : ''}

    ${meeting.minutes ? `<h3 style="color: #081F3F; margin-bottom: 8px;">Meeting Minutes</h3><p style="background: #f5f5f5; padding: 12px; border-radius: 6px; white-space: pre-wrap; margin: 0 0 20px;">${meeting.minutes}</p>` : ''}

    ${meeting.action_items ? `
    <div style="background: #fff3e0; border-left: 4px solid #f57c00; padding: 16px; border-radius: 0 6px 6px 0; margin-bottom: 20px;">
      <h3 style="color: #e65100; margin: 0 0 8px;">⚡ Action Items</h3>
      <p style="white-space: pre-wrap; margin: 0;">${meeting.action_items}</p>
    </div>` : ''}

    ${meeting.follow_up_date ? `<p style="color: #666;"><strong>Follow-Up Date:</strong> ${meeting.follow_up_date}</p>` : ''}

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #eee;" />
    <p style="color: #999; font-size: 12px;">This summary was automatically generated by FundaMedical Sales Hub.</p>
  </div>
</body></html>`;

    const recipients = emails || [];
    if (meeting.client_contact_email) recipients.push(meeting.client_contact_email);
    const uniqueRecipients = [...new Set(recipients.filter(Boolean))];

    const results = await Promise.allSettled(
      uniqueRecipients.map(to =>
        base44.asServiceRole.integrations.Core.SendEmail({ to, subject, body })
      )
    );

    const sent = results.filter(r => r.status === 'fulfilled').length;
    return Response.json({ success: true, sent, total: uniqueRecipients.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});